#!/usr/bin/env python3
"""Build eth_dhcp guest firmware for M0+ / M33 / RV32 without any
cross-toolchain: assemble with clang (ARM + RISC-V targets ship with the
system clang), lay out the flat binary in Python (vectors + code + rodata
+ data), convert with uf2conv.py.

Outputs (web/ only — web/ is git-tracked and is what sweep runs):
  web/eth_dhcp.uf2            RP2040 M0+  family 0xE48BFF56
  web/eth_dhcp_pico2.uf2      RP2350 M33  family 0xE48BFF59
  web/eth_dhcp_rv32.uf2       RP2350 RV32 family 0xE48BFF5A

Guest sources are generated by gen_eth_dhcp.py (single source of truth
for the DHCP flow); this script only assembles/links/converts. Run
`python3 test-firmware/gen_eth_dhcp.py` first after editing the generator.

Layout (ARM):
  vectors @0x10000100: SP, reset+1, 14x 0xFFFFFFFF (64B)
  .text follows, then .rodata, then .data (yiaddr/server state).
  NOTE: the .bin is a raw flash image; .data is linked at its flash
  address but the image has no startup copier — the guest treats .data
  as read-mostly constants EXCEPT yip_addr/sip_addr which parse_offer
  overwrites in place (flash writes are ignored by the emulator, but
  the addresses also alias SRAM? NO — they are flash addresses).
  See build_eth.py data handling below.
  Relocations handled: R_ARM_ABS32 (ldr =addr, .word addr), R_ARM_THM_CALL
  (bl), R_ARM_THM_JUMP24/11 (b), R_ARM_THM_MOVW/MOVT_ABS_NC (movw/movt).
Layout (RV32, same as rvlink.py): .text @0x10000000, .rodata after.
  Relocations handled: R_RISCV_JAL/BRANCH/HI20/LO12/PCREL_* (subset used).
"""
import os
import re
import struct
import subprocess
import sys

D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(D)

CLANG = "clang"

# ---------------------------------------------------------------- ARM utils

def read_elf_sections(path):
    """Parse ELF32 section headers -> {name: (offset, size, addr_align...)}."""
    d = open(path, "rb").read()
    assert d[:4] == b"\x7fELF", path
    e_shoff, = struct.unpack("<I", d[0x20:0x24])
    e_shentsize, e_shnum, e_shstrndx = struct.unpack("<HHH", d[0x2E:0x34])
    secs = []
    for i in range(e_shnum):
        o = e_shoff + i * e_shentsize
        (name, typ, flags, addr, off, size, link, info, al, es) = struct.unpack(
            "<IIIIIIIIII", d[o:o + 40])
        secs.append(dict(idx=i, name=name, type=typ, flags=flags, addr=addr,
                         off=off, size=size, link=link, info=info, al=al, es=es))
    sh = secs[e_shstrndx]
    shstr = d[sh["off"]:sh["off"] + sh["size"]]
    for s in secs:
        s["nm"] = shstr[s["name"]:].split(b"\0")[0]
    return d, secs


ARCH_CFLAGS = {
    # family: (clang-target, march, extra cflags)
    0xE48BFF56: ("armv6m-none-eabi", "armv6m", []),
    0xE48BFF59: ("armv8m.main-none-eabi", "armv8-m.main", ["-DRP2350"]),
}


def arm_build(asm_path, family, out_uf2, extra_cflags=()):
    target, march, archflags = ARCH_CFLAGS[family]
    obj = asm_path + ".o"
    cmd = [CLANG, f"--target={target}", f"-march={march}", "-mthumb",
           "-c", asm_path, "-o", obj] + archflags + list(extra_cflags)
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        raise SystemExit(f"clang failed for {asm_path}")
    d, secs = read_elf_sections(obj)
    byname = {s["nm"]: s for s in secs}
    for need in (b".vectors", b".text"):
        assert need in byname, f"{asm_path}: missing {need}"
    vec, text = byname[b".vectors"], byname[b".text"]
    rodata = byname.get(b".rodata")
    vec_bytes = bytearray(d[vec["off"]:vec["off"] + vec["size"]])
    assert len(vec_bytes) == 64, len(vec_bytes)
    tbytes = bytearray(d[text["off"]:text["off"] + text["size"]])
    rbytes = d[rodata["off"]:rodata["off"] + rodata["size"]] if rodata else b""
    # layout: vectors@0x10000100, text@+0x40, rodata after (align 4)
    tbase = 0x10000100 + 64
    rbase = (tbase + len(tbytes) + 3) & ~3
    secbase = {vec["idx"]: 0x10000100, text["idx"]: tbase}
    if rodata:
        secbase[rodata["idx"]] = rbase
    # symbols for ABS32.
    # NOTE: ELF section indices in st_shndx are 1-based (0=undef, with
    # the NULL section at index 0), but our `secs` list is 0-based and
    # INCLUDES the NULL section as secs[0] — so secs[st_shndx] is the
    # right entry and secbase must be keyed by ELF index, not list
    # position. (secbase uses s["idx"], which IS the ELF index.)
    syms = []
    for s in secs:
        if s["type"] == 2:  # SYMTAB
            for j in range(s["size"] // 16):
                e = d[s["off"] + j * 16:s["off"] + (j + 1) * 16]
                st_name, st_value, st_size, st_info, st_other, st_shndx = \
                    struct.unpack("<IIIBBH", e)
                syms.append((st_shndx, st_value))
    # relocations (REL type=4 legacy, RELA/REL-with-addend type=9 on clang)
    for s in secs:
        if s["type"] not in (4, 9):  # REL / RELA
            continue
        for j in range(s["size"] // s["es"]):
            e = d[s["off"] + j * s["es"]:s["off"] + (j + 1) * s["es"]]
            r_off, r_info = struct.unpack("<II", e)
            rtype, symidx = r_info & 0xFF, r_info >> 8
            # s["info"] is the target section ELF index (REL semantics).
            # secs[] is 0-based INCLUDING the NULL section, so ELF index
            # == list position here; look up explicitly to be safe.
            ts = next(s2 for s2 in secs if s2["idx"] == s["info"])
            base = secbase.get(s["info"])
            if base is None or ts["nm"] not in (b".vectors", b".text"):
                continue
            buf = vec_bytes if ts["nm"] == b".vectors" else tbytes
            shndx, val = syms[symidx]
            # st_shndx is an ELF section INDEX; secbase is keyed by the
            # same index (s["idx"]). A symbol in .text (idx 2) therefore
            # resolves to tbase+st_value — NOT to an RSI-style table.
            # (An older draft indexed secbase by list position, which
            # silently mapped .text->0 and sent every bl to 0x000000.)
            S = secbase.get(shndx, 0) + val if shndx else 0
            P = base + r_off
            if rtype == 2:  # R_ARM_ABS32
                cur, = struct.unpack("<I", buf[r_off:r_off + 4])
                struct.pack_into("<I", buf, r_off, (cur + S) & 0xFFFFFFFF)
            elif rtype == 10:  # R_ARM_THM_CALL (BL resolved at link time)
                T = S & ~1
                off = T - (P + 4)
                assert -(1 << 24) <= off < (1 << 24) and off % 2 == 0, (hex(off), hex(S), hex(P))
                S_imm = off >> 1
                J1 = 1 if not (((S_imm >> 22) ^ (S_imm >> 23)) & 1) else 0
                J2 = 1 if not (((S_imm >> 21) ^ (S_imm >> 23)) & 1) else 0
                imm10 = (S_imm >> 11) & 0x3FF
                imm11 = S_imm & 0x7FF
                Sbit = (S_imm >> 23) & 1
                # BL (not BLX): second halfword base is 0xF800
                hi = 0xF000 | (Sbit << 10) | imm10
                lo = 0xF800 | (J1 << 13) | (J2 << 11) | imm11
                struct.pack_into("<HH", buf, r_off, hi, lo)
            elif rtype in (28, 29, 30):  # CALL/JUMP24/JUMP11
                # Thumb BL/B: decode, recompute offset to S
                if rtype == 30:  # 16-bit B
                    h, = struct.unpack("<H", buf[r_off:r_off + 2])
                    imm11 = h & 0x7FF
                    if imm11 & 0x400:
                        imm11 -= 0x800
                    # S = target; BL target has thumb bit set sometimes
                    T = S & ~1
                    off = T - (P + 4)
                    assert -(1 << 11) <= off < (1 << 11) and off % 2 == 0, hex(off)
                    buf[r_off] = (h & 0xF8) | ((off >> 1) & 0x7FF) & 0xFF
                    struct.pack_into("<H", buf, r_off,
                                     (h & 0xF800) | (((off >> 1) & 0x7FF)))
                else:  # 32-bit BL (or JUMP24 same encoding)
                    hi, lo = struct.unpack("<HH", buf[r_off:r_off + 4])
                    # original addend: S_ = S - ... simpler: recompute from S
                    T = S & ~1
                    off = T - (P + 4)
                    assert -(1 << 24) <= off < (1 << 24) and off % 2 == 0, hex(off)
                    S_imm = off >> 1  # 23-bit signed
                    J1 = 1 if not (((S_imm >> 22) ^ (S_imm >> 23)) & 1) else 0
                    J2 = 1 if not (((S_imm >> 21) ^ (S_imm >> 23)) & 1) else 0
                    imm10 = (S_imm >> 11) & 0x3FF
                    imm11 = S_imm & 0x7FF
                    Sbit = (S_imm >> 23) & 1
                    hi = 0xF000 | (Sbit << 10) | imm10
                    lo = 0xE800 | (J1 << 13) | (J2 << 11) | imm11
                    struct.pack_into("<HH", buf, r_off, hi, lo)
            elif rtype in (43, 44):  # MOVW/MOVT ABS_NC
                h, = struct.unpack("<H", buf[r_off:r_off + 2])
                # encoding: movw Rd, #imm16 -> imm4 in hi[3:0], imm8 in lo[7:0]... use full recompute
                lo = buf[r_off + 2] | (buf[r_off + 3] << 8)
                if rtype == 43:
                    imm = S & 0xFFFF
                else:
                    imm = (S >> 16) & 0xFFFF
                imm4 = (imm >> 12) & 0xF
                ibit = (imm >> 11) & 1
                imm3 = (imm >> 8) & 0x7
                imm8 = imm & 0xFF
                hi = (h & 0xFBF0) | (ibit << 10) | imm4
                lo = (lo & 0xF800) | (imm3 << 12) | imm8
                buf[r_off] = hi & 0xFF
                buf[r_off + 1] = hi >> 8
                buf[r_off + 2] = lo & 0xFF
                buf[r_off + 3] = lo >> 8
            else:
                raise SystemExit(f"unsupported ARM reloc {rtype}")
    # .data (writable state) must ALSO be in the image: lay out
    # vectors/text/rodata/data contiguously; .data addrs are flash addrs
    # (firmware never writes them — SRAM aliases YIP/SIP are used).
    data = byname.get(b".data")
    dbytes = d[data["off"]:data["off"] + data["size"]] if data else b""
    dbase = (rbase + len(rbytes) + 3) & ~3 if data else rbase
    if data:
        secbase[data["idx"]] = dbase
    img = bytes(vec_bytes) + bytes(tbytes)
    img += b"\0" * (rbase - (tbase + len(tbytes)))
    img += bytes(rbytes)
    if data:
        img += b"\0" * (dbase - (rbase + len(rbytes)))
        img += bytes(dbytes)
    binpath = asm_path + ".bin"
    open(binpath, "wb").write(img)
    r = subprocess.run([sys.executable, os.path.join(D, "uf2conv.py"), binpath,
                        "-o", out_uf2, "-b", "0x10000100", "-f", hex(family)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        raise SystemExit("uf2conv failed")
    print(f"wrote {out_uf2} ({len(img)}B)")


# ---------------------------------------------------------------- RV32 utils

def rv_build(asm_path, out_uf2):
    obj = asm_path + ".o"
    cmd = [CLANG, "--target=riscv32-unknown-elf", "-march=rv32ima",
           "-mabi=ilp32", "-c", asm_path, "-o", obj]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
        raise SystemExit(f"clang failed for {asm_path}")
    r = subprocess.run([sys.executable, os.path.join(D, "rvlink.py"), obj,
                        asm_path + ".bin"], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        raise SystemExit("rvlink failed")
    r = subprocess.run([sys.executable, os.path.join(D, "uf2conv.py"),
                        asm_path + ".bin", "-o", out_uf2,
                        "-b", "0x10000000", "-f", "0xE48BFF5A"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        raise SystemExit("uf2conv failed")
    print(f"wrote {out_uf2}")


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Build eth_dhcp UF2s (M0+/M33/RV32)")
    ap.add_argument("--gen", action="store_true",
                    help="regenerate eth_dhcp.S + eth_dhcp_rv32.S first")
    ap.add_argument("which", nargs="*", default=["all"],
                    help="m0, m33, rv32, or all")
    args = ap.parse_args()
    if args.gen:
        sys.path.insert(0, D)
        import gen_eth_dhcp
        gen_eth_dhcp.main()
    want = set(args.which)
    if "all" in want:
        want = {"m0", "m33", "rv32"}
    if "m0" in want:
        arm_build(os.path.join(D, "eth_dhcp.S"), 0xE48BFF56,
                  os.path.join(ROOT, "web", "eth_dhcp.uf2"))
    if "m33" in want:
        arm_build(os.path.join(D, "eth_dhcp.S"), 0xE48BFF59,
                  os.path.join(ROOT, "web", "eth_dhcp_pico2.uf2"))
    if "rv32" in want:
        rv_build(os.path.join(D, "eth_dhcp_rv32.S"),
                 os.path.join(ROOT, "web", "eth_dhcp_rv32.uf2"))


if __name__ == "__main__":
    main()
