#!/usr/bin/env python3
"""Shared constants + frame builders for the eth_http E2E test.

eth_http guests (M0+/M33/RV32, generated by gen_eth_dhcp.py) do a full
DHCP DORA (same blobs/lease pool as eth_dhcp: .2 / server .1), then run
an HTTP client over W5500 MACRAW socket 0:

  guest: ARP who-has .1 -> SYN .1:80 -> ACK -> GET / -> await 200 hello-eth
         -> ACK -> FIN -> await FIN-ACK -> final ACK -> ETH HTTP-DONE

http_peer_test.py plays DHCP server + gateway (.1) + TCP:80 server. It
mirrors test-firmware/ws_peer_test.py (the WiFi webserver E2E) with the
client/server roles kept: there the *peer* is the TCP client and the
RV32 *guest* serves; here the *guest* is the TCP client and the *peer*
serves. Same checksums, same FIN dance, same body style.

Per-arch identity matches eth_dhcp (ARCHES in gen_eth_dhcp.py) so the
three sweep runs don't cross-talk on a shared room:
  sport: M0=0xE100 M33=0xE101 RV32=0xE102
  cseq (guest initial SEQ): the arch XID bytes as a BE u32
  sseq (peer initial SEQ): 0x00100000 (mirrors webserver _WS_SEQ)

All guest TCP frames are static blobs (checksums precomputed here) —
same pattern as the DHCP blobs. The peer always uses the fixed SSEQ,
so the guest never builds checksums at runtime; it only parses.
"""

import struct

SRV_MAC = bytes([0x5A, 0x94, 0xEF, 0xE4, 0x0C, 0xDD])  # gateway MAC (handleDHCP.go)
SRV_IP = bytes([192, 168, 4, 1])
LEASE_IP = bytes([192, 168, 4, 2])

SSEQ = 0x00100000

HTTP_ARCHES = {
    "m0": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x60]),
               xid=bytes([0xA0, 0xB0, 0xC0, 0xD0]), sport=0xE100),
    "m33": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x61]),
                xid=bytes([0xB0, 0xB1, 0xC0, 0xD1]), sport=0xE101),
    "rv32": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x62]),
                 xid=bytes([0xC0, 0xB2, 0xC0, 0xD2]), sport=0xE102),
}

GET_REQ = b"GET / HTTP/1.0\r\n\r\n"  # 18B, guest sends exactly this
HTTP_HDR = b"HTTP/1.0 200 OK\r\nContent-Length: 9\r\nConnection: close\r\n\r\n"
HTTP_BODY = b"hello-eth"  # 9B, guest scans payload for this
HTTP_PAYLOAD = HTTP_HDR + HTTP_BODY
assert len(GET_REQ) == 18, len(GET_REQ)
assert len(HTTP_HDR) == 57, len(HTTP_HDR)
assert len(HTTP_PAYLOAD) == 57 + 9, len(HTTP_PAYLOAD)  # 57B header + 9B body
HTTP_PREFIX = b"HTTP/1.0 200"  # 12B, guest checks these bytes first


def csum(data):
    s = 0
    for i in range(0, len(data) - 1, 2):
        s += (data[i] << 8) + data[i + 1]
    if len(data) & 1:
        s += data[-1] << 8
    while s >> 16:
        s = (s & 0xFFFF) + (s >> 16)
    return (~s) & 0xFFFF


def verify_ip(ip):
    return csum(ip) == 0


def verify_tcp(src, dst, seg):
    pseudo = src + dst + bytes([0, 6]) + struct.pack(">H", len(seg))
    return csum(pseudo + seg) == 0


def eth(dst, src, etype, payload):
    return dst + src + struct.pack(">H", etype) + payload


def build_arp_req(mac):
    """Guest ARP who-has .1 (42B)."""
    assert len(mac) == 6
    return (eth(bytes([0xFF] * 6), mac, 0x0806,
                struct.pack(">HHBBH", 1, 0x0800, 6, 4, 1) + mac +
                LEASE_IP + bytes(6) + SRV_IP))


def _tcp_blob(mac, sport, seq, ack, flags, payload=b""):
    """Guest->server TCP frame (ETH+IP+TCP+payload), checksums filled."""
    seg = struct.pack(">HHIIBBHHH", sport, 80, seq, ack, 5 << 4, flags,
                      8192, 0, 0) + payload
    tcplen = len(seg)
    pseudo = LEASE_IP + SRV_IP + bytes([0, 6]) + struct.pack(">H", tcplen)
    cs = csum(pseudo + seg)
    seg = seg[:16] + struct.pack(">H", cs) + seg[18:]
    ip = bytearray([0x45, 0]) + struct.pack(">H", 20 + len(seg))
    ip += struct.pack(">HHHH", 0x0001, 0, 64 * 256 + 6, 0) + LEASE_IP + SRV_IP
    cs = csum(bytes(ip))
    ip[10], ip[11] = (cs >> 8) & 0xFF, cs & 0xFF
    return eth(SRV_MAC, mac, 0x0800, bytes(ip) + seg)


def build_syn(mac, sport, cseq):
    """Guest SYN (54B)."""
    return _tcp_blob(mac, sport, cseq, 0, 0x02)


def build_ack(mac, sport, cseq, sseq):
    """Guest handshake ACK: seq cseq+1, ack sseq+1 (54B)."""
    return _tcp_blob(mac, sport, (cseq + 1) & 0xFFFFFFFF,
                     (sseq + 1) & 0xFFFFFFFF, 0x10)


def build_get(mac, sport, cseq, sseq):
    """Guest GET (54+18=72B)."""
    return _tcp_blob(mac, sport, (cseq + 1) & 0xFFFFFFFF,
                     (sseq + 1) & 0xFFFFFFFF, 0x18, GET_REQ)


def build_ack2(mac, sport, cseq, sseq):
    """Guest ACK of HTTP data: seq cseq+19, ack sseq+67 (54B)."""
    return _tcp_blob(mac, sport, (cseq + 19) & 0xFFFFFFFF,
                     (sseq + 67) & 0xFFFFFFFF, 0x10)


def build_fin(mac, sport, cseq, sseq):
    """Guest FIN: seq cseq+19, ack sseq+67, FIN+ACK (54B)."""
    return _tcp_blob(mac, sport, (cseq + 19) & 0xFFFFFFFF,
                     (sseq + 67) & 0xFFFFFFFF, 0x11)


def build_fack(mac, sport, cseq, sseq):
    """Guest final ACK: seq cseq+20, ack sseq+68 (54B)."""
    return _tcp_blob(mac, sport, (cseq + 20) & 0xFFFFFFFF,
                     (sseq + 68) & 0xFFFFFFFF, 0x10)


def cseq_of(xid):
    return struct.unpack(">I", bytes(xid))[0]


def parse_tcp_from_guest(f, sport_guest):
    """Parse + verify a guest->server TCP frame. Returns dict or None."""
    if len(f) < 14 + 20 + 20:
        return None
    if f[12:14] != b"\x08\x00":
        return None
    ip = f[14:]
    if ip[9] != 6:
        return None
    ihl = (ip[0] & 0xF) * 4
    if ihl < 20 or len(ip) < ihl:
        return None
    if not verify_ip(ip[:ihl]):
        print("WARN: bad guest IP checksum")
        return None
    if ip[12:16] != LEASE_IP or ip[16:20] != SRV_IP:
        return None
    iplen = (ip[2] << 8) + ip[3]
    seg = ip[ihl:ihl + (iplen - ihl)]
    if len(seg) < 20:
        return None
    if not verify_tcp(ip[12:16], ip[16:20], seg):
        print("WARN: bad guest TCP checksum")
        return None
    sport, dport, seq, ack, off, flags = struct.unpack(">HHIIBB", seg[:14])
    if sport != sport_guest or dport != 80:
        return None
    hlen = (off >> 4) * 4
    return {"seq": seq, "ack": ack, "flags": flags, "payload": seg[hlen:]}


def is_arp_who_has(f, gmac):
    """Guest ARP who-has .1? Returns (mac, ip) or None."""
    if len(f) < 42 or f[12:14] != b"\x08\x06":
        return None
    if f[20:22] != b"\x00\x01":
        return None
    if f[38:42] != SRV_IP:
        return None
    if f[22:28] != gmac:
        return None
    if f[28:32] != LEASE_IP:
        return None
    return f[22:28], f[28:32]


def arp_reply(gmac, gip):
    """ARP reply: .1 (SRV_MAC) is-at .1, for guest gmac/gip."""
    return eth(gmac, SRV_MAC, 0x0806,
               struct.pack(">HHBBH", 1, 0x0800, 6, 4, 2) + SRV_MAC + SRV_IP +
               gmac + gip)


def tcp_seg_from_srv(sport_guest, seq, ack, flags, payload=b""):
    """TCP segment from server :80 to guest sport, IPs .1 -> .2."""
    seg = struct.pack(">HHIIBBHHH", 80, sport_guest, seq, ack, 5 << 4,
                      flags, 8192, 0, 0)
    tcplen = len(seg) + len(payload)
    pseudo = SRV_IP + LEASE_IP + bytes([0, 6]) + struct.pack(">H", tcplen)
    cs = csum(pseudo + seg + payload)
    seg = seg[:16] + struct.pack(">H", cs) + seg[18:]
    return seg + payload


def ip_pkt_from_srv(gmac, seg):
    ip = bytearray([0x45, 0]) + struct.pack(">H", 20 + len(seg))
    ip += struct.pack(">HHHH", 0x1234, 0, 64 * 256 + 6, 0) + SRV_IP + LEASE_IP
    cs = csum(bytes(ip))
    ip[10], ip[11] = (cs >> 8) & 0xFF, cs & 0xFF
    return eth(gmac, SRV_MAC, 0x0800, bytes(ip) + seg)
