#!/usr/bin/env python3
"""Generate ble_adv ARM guest: BLE advertise+scan over CYW43 BT shared bus
(PIO gSPI backplane, func=1) for M0+ / M33.

Writes test-firmware/ble_adv.S (RP2040 ifdefs; M0+ v6m-safe / M33).

ARM port of the proven RV32 ble_adv_rv32 path (gen_rv32.py). Same BT
bring-up over the gSPI backplane (func=1): BT_CTRL/HOST_CTRL handshake,
RAM-base discovery, index init, then HCI RESET, ADV_PARAMS, ADV_DATA
(name BARM), ADV_ENABLE, SCAN_PARAMS, SCAN_ENABLE with Command Complete
waits. Prints markers; with a vnet peer (-net -net-peer) a second
instance's ADV arrives as 0x88B5 and is reported (SCAN-OK).

PIO: PIO0 SM0 on BOTH chips (0x50200000; autodetect via PINCTRL
sideset_base=29). UART/SRAM differ per arch (ifdefs).

Markers (arch-neutral): ARM BLE Starting / BT-CTRL / RAM-BASE /
HOST-READY / RESET-OK / ADV-OK / LISTEN / SCAN-OK / SCAN-TIMEOUT /
CC-FAIL. Sweep greps ARM BLE LISTEN (local bring-up, no peer needed).

v6m rules: adds #imm<=7 for pointer bumps (larger via literals),
cmp #imm<=255, balanced push/pop, .ltorg within ~1KB of each pool.

Run: python3 test-firmware/gen_ble_arm.py (writes ble_adv.S).
Then: python3 test-firmware/build_eth.py ble-m0 / ble-m33.
"""
import os

D = os.path.dirname(os.path.abspath(__file__))

ARM_SRC = r"""/*
 * ble_adv — BLE advertise+scan over CYW43 BT shared bus (PIO gSPI).
 * Generated by gen_ble_arm.py - do not hand-edit (edit the generator).
 *
 * ARM (M0+/M33) port of the proven RV32 ble_adv_rv32 path: BT bring-up
 * over the gSPI backplane (func=1) via PIO0 SM0, then HCI RESET,
 * ADV_PARAMS, ADV_DATA (BARM), ADV_ENABLE, SCAN_PARAMS, SCAN_ENABLE
 * with Command Complete waits. Prints markers; SCAN-OK on LE
 * Advertising Report (ev 3E sub 02) from a peer.
 *
 * Two builds from this one source (RP2040 ifdefs):
 *   M0+   (RP2040): UART0 0x40034000 RAM_TOP 0x20042000
 *   M33   (RP2350): UART0 0x40070000 RAM_TOP 0x20082000
 * PIO0 0x50200000 on both (autodetect sideset_base=29).
 * Assemble M33 with -DRP2350 (build.sh _pico2 pattern, build_eth.py).
 */
.syntax unified
#ifdef RP2350
.cpu cortex-m33
#else
.cpu cortex-m0plus
#endif
.thumb

#ifdef RP2350
.equ UART0_DR,    0x40070000
.equ UART0_CR,    0x40070030
.equ RAM_TOP,     0x20082000
.equ RXBUF,       0x20081000
.equ TXBUF,       0x20081400
.equ STATE_BASE,  0x20081800
#else
.equ UART0_DR,    0x40034000
.equ UART0_CR,    0x40034030
.equ RAM_TOP,     0x20042000
.equ RXBUF,       0x2003E000
.equ TXBUF,       0x2003E400
.equ STATE_BASE,  0x2003E800
#endif
/* STATE_BASE+0 = B2H_OUT shadow, +4 = H2B_IN shadow */
.equ STATE_B2H,   STATE_BASE
.equ STATE_H2B,   STATE_BASE + 4
.equ UART_CR_EN,  0x0301
.equ PIO0_BASE,   0x50200000
.equ PIO0_CTRL,   0x50200000
.equ PIO0_FSTAT,  0x50200004
.equ PIO0_TXF0,   0x50200010
.equ PIO0_RXF0,   0x50200020
.equ PIO0_SM0_PINCTRL, 0x502000DC
.equ FSTAT_RXEMPTY0, 0x100

.section .vectors, "a", %progbits
.align 2
_vectors:
.word RAM_TOP
.word reset_handler + 1
.word 0xFFFFFFFF
.word 0xFFFFFFFF
.rept 12
.word 0xFFFFFFFF
.endr

.section .text
.align 2

/* reset_handler: UART + PIO setup, BT bring-up, HCI sequence, scan.
 * NOTE: all PIO0 FIFO traffic uses ABSOLUTE addresses (PIO0_TXF0 /
 * PIO0_RXF0) with the base in the pointer register. The RV32 original
 * keeps PIO base in s0 and TXF0 in s1 as separate registers; on ARM we
 * MUST NOT recompute TXF0 as base+reg (e.g. adds r1,r1,r0 corrupts the
 * FIFO address — TXF writes then land nowhere and every gSPI command
 * reads back addr=0 size=0). */
.thumb_func
.global reset_handler
reset_handler:
ldr r7, =RAM_TOP; mov sp, r7
ldr r4, =UART0_CR; ldr r5, =UART_CR_EN; str r5, [r4]
ldr r0, =msg_start; bl print_string
/* PIO0 SM0 setup for gSPI detect: PINCTRL sideset_base=29 (29<<10).
 * NOTE: NO TXF dummy traffic here (and NO CTRL restart either — PIO
 * CTRL bit 4 = SM_RESTART strobe). The RV32 original does two dummy
 * swap-read rounds (TXF=31,31,A0044000 + RXF) for its DMA engine, but
 * on ARM PIO-MMIO each TXF word feeds the CYW43 intercept directly:
 * the dummy 31/31 words decode as a bogus gSPI command and burn the
 * 2-command SWAP32 budget (pio_init_swap_remaining), so every real
 * command afterwards decodes with the wrong byte order. PINCTRL alone
 * is enough for autodetect. */
ldr r0, =PIO0_SM0_PINCTRL
ldr r1, =0x7400
str r1, [r0]
/* shadows B2H_OUT=0 H2B_IN=0 */
ldr r0, =STATE_BASE
movs r1, #0
str r1, [r0]
str r1, [r0, #4]
/* window 0x18000000 (BT regs): BT_CTRL @0x0C7C */
ldr r0, =0x18000000; bl ba_window
ldr r0, =0x0C7C; bl ba_rd32
mov r4, r0
ldr r0, =msg_btctrl; bl print_string
mov r0, r4; bl print_hex32
/* RAM-BASE @0x0D68 */
ldr r0, =0x0D68; bl ba_rd32
mov r4, r0
ldr r0, =msg_rambase; bl print_string
mov r0, r4; bl print_hex32
/* HOST_CTRL @0x0D6C |= 1 */
ldr r0, =0x0D6C; bl ba_rd32
movs r1, #1
orrs r0, r1
mov r4, r0
ldr r0, =0x0D6C; mov r1, r4; bl ba_wr32
/* window 0x001C0000 (BT RAM): zero H2B_IN/OUT + B2H_IN/OUT */
ldr r0, =0x001C0000; bl ba_window
ldr r0, =0x2000; movs r1, #0; bl ba_wr32
ldr r0, =0x2004; movs r1, #0; bl ba_wr32
ldr r0, =0x2008; movs r1, #0; bl ba_wr32
ldr r0, =0x200C; movs r1, #0; bl ba_wr32
ldr r0, =msg_hostready; bl print_string
/* HCI RESET (0x0C03, no params) */
ldr r0, =0x0C03; movs r1, #0; movs r2, #0; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_reset_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_reset_ok:
ldr r0, =msg_resetok; bl print_string
/* LE_SET_ADV_PARAMS (0x2006, 15B) */
ldr r0, =blob_adv_params
mov r4, r0
ldr r0, =0x2006; mov r1, r4; movs r2, #15; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_advp_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_advp_ok:
/* LE_SET_ADV_DATA (0x2008, 32B: flags + BARM) */
ldr r0, =blob_adv_data
mov r4, r0
ldr r0, =0x2008; mov r1, r4; movs r2, #32; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_advd_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_advd_ok:
/* LE_SET_ADV_ENABLE (0x200A, 1B: 01) */
ldr r0, =blob_adv_en
mov r4, r0
ldr r0, =0x200A; mov r1, r4; movs r2, #1; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_adve_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_adve_ok:
ldr r0, =msg_advok; bl print_string
/* LE_SET_SCAN_PARAMS (0x200B, 7B) */
ldr r0, =blob_scan_params
mov r4, r0
ldr r0, =0x200B; mov r1, r4; movs r2, #7; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_scanp_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_scanp_ok:
/* LE_SET_SCAN_ENABLE (0x200C, 2B: 01 00) */
ldr r0, =blob_scan_en
mov r4, r0
ldr r0, =0x200C; mov r1, r4; movs r2, #2; bl ba_hci
bl ba_wait_cc
cmp r0, #0
beq hci_scane_ok
ldr r0, =msg_ccfail; bl print_string; b halt_fail
hci_scane_ok:
ldr r0, =msg_listen; bl print_string
/* scan loop: bounded poll for LE Advertising Report (ev 3E sub 02) */
ldr r5, =4000000
scan_loop:
bl ba_poll_b2h
cmp r0, #0
beq scan_next
bl ba_read_ev
ldr r0, =RXBUF
ldrb r1, [r0]
cmp r1, #0x3E
bne scan_next
adds r0, #1
adds r0, #1
ldrb r1, [r0]
cmp r1, #0x02
bne scan_next
ldr r0, =msg_scanok; bl print_string; b halt_ok
scan_next:
subs r5, #1
bne scan_loop
ldr r0, =msg_scantimeout; bl print_string; b halt_ok
halt_fail:
b halt_fail
halt_ok:
b halt_ok
.ltorg

/* ---------- ba_bswap: r0 = bswap32(r0). Preserves r1-r3.
 * Used on BOTH paths: TX words are bswapped (DMA-BSWAP emulation —
 * the SDK's dma_channel_set_bswap does this in hardware; ARM PIO-MMIO
 * guests must do it in software) and RX words are unswapped back. */
.thumb_func
ba_bswap:
push {r1-r3,lr}
mov r1, r0
lsrs r0, r1, #24
lsls r2, r1, #24
orrs r0, r2
lsrs r2, r1, #8
ldr r3, =0xFF00
ands r2, r3
orrs r0, r2
lsrs r2, r1, #16
ldr r3, =0xFF
ands r2, r3
lsls r2, #16
orrs r0, r2
lsrs r2, r1, #16
ldr r3, =0xFF
ands r2, r3
lsls r2, #8
orrs r0, r2
pop {r1-r3,pc}
.ltorg

/* ---------- ba_pio_wr_pre: PIO WR prologue (X/Y skip words).
 * Writes the 2 pre-DMA bit-count words the CYW43 intercept skips
 * (pio_pre_dma_skip, re-armed by every SM restart). Clobbers r0-r1.
 * The CTRL restart (bit 4 = SM_RESTART) is REQUIRED before the skip
 * words: the restart is what re-arms the intercept's 2-word skip for
 * the next transfer (RV32 rhythm). Verified by A/B probe on ARM
 * PIO-MMIO: restart + 2 skip words decodes every transfer; either
 * piece alone shifts the stream (addr=0 size=0, or addr=0x3FE0). */
.thumb_func
ba_pio_wr_pre:
push {r0-r1,lr}
ldr r0, =PIO0_CTRL
movs r1, #0x11
lsls r1, #4
str r1, [r0]
ldr r0, =PIO0_TXF0
movs r1, #0xFF
lsls r1, #1
adds r1, #1
str r1, [r0]
movs r1, #0
str r1, [r0]
pop {r0-r1,pc}
.ltorg

/* ---------- ba_cmd: r0 = raw gSPI cmd word -> TXF (bswapped, like
 * the SDK DMA engine's channel_config_set_bswap). Preserves r1. ------ */
.thumb_func
ba_cmd:
push {r1-r2,lr}
mov r2, r1
bl ba_bswap
ldr r1, =PIO0_TXF0
str r0, [r1]
mov r1, r2
pop {r1-r2,pc}
.ltorg

/* ---------- ba_wdata: r0 = data word (host order) -> TXF (bswapped).
 * Preserves r1 (same contract as ba_cmd). ---------- */
.thumb_func
ba_wdata:
push {r1-r2,lr}
mov r2, r1
bl ba_bswap
ldr r1, =PIO0_TXF0
str r0, [r1]
mov r1, r2
pop {r1-r2,pc}
.ltorg

/* ---------- ba_window: r0 = 32-bit backplane base. 3 byte-writes.
 * Clobbers r0-r1 via callees; uses r4-r5 (saved). ---------- */
.thumb_func
ba_window:
push {r4-r5,lr}
mov r4, r0
lsrs r0, r4, #8
ldr r1, =0xFF
ands r0, r1
mov r5, r0
bl ba_pio_wr_pre
ldr r0, =0xD8005004
bl ba_cmd
mov r0, r5
bl ba_wdata
lsrs r0, r4, #16
ldr r1, =0xFF
ands r0, r1
mov r5, r0
bl ba_pio_wr_pre
ldr r0, =0xD8005804
bl ba_cmd
mov r0, r5
bl ba_wdata
lsrs r0, r4, #24
mov r5, r0
bl ba_pio_wr_pre
ldr r0, =0xD8006004
bl ba_cmd
mov r0, r5
bl ba_wdata
pop {r4-r5,pc}
.ltorg

/* ---------- ba_wr32: r0 = 15-bit offset, r1 = value. ---------- */
.thumb_func
ba_wr32:
push {r4-r6,lr}
mov r4, r0
mov r5, r1
lsls r0, r4, #11
ldr r1, =0xD0000004
orrs r0, r1
mov r6, r0
bl ba_pio_wr_pre
mov r0, r6
bl ba_cmd
mov r0, r5
bl ba_wdata
pop {r4-r6,pc}
.ltorg

/* ---------- ba_rd32: r0 = 15-bit offset -> r0 = value. ---------- */
.thumb_func
ba_rd32:
push {r4-r5,lr}
mov r4, r0
lsls r0, r4, #11
ldr r1, =0x50000004
orrs r0, r1
mov r5, r0
bl ba_pio_wr_pre
mov r0, r5
bl ba_cmd
ldr r5, =20000
rd32_poll:
ldr r0, =PIO0_FSTAT
ldr r1, [r0]
ldr r0, =0x100
tst r1, r0
beq rd32_got
subs r5, #1
bne rd32_poll
movs r0, #0
pop {r4-r5,pc}
rd32_got:
ldr r0, =PIO0_RXF0
ldr r1, [r0]
ldr r1, [r0]
ldr r1, [r0]
ldr r1, [r0]
ldr r0, [r0]
bl ba_bswap
pop {r4-r5,pc}
.ltorg

/* ---------- ba_wr_bulk: r0 = offset, r1 = src, r2 = len (mult of 4).
 * ---------- */
.thumb_func
ba_wr_bulk:
push {r4-r7,lr}
mov r4, r0
mov r5, r1
mov r6, r2
lsls r0, r4, #11
ldr r1, =0xD0000000
orrs r0, r1
orrs r0, r6
mov r7, r0
bl ba_pio_wr_pre
mov r0, r7
bl ba_cmd
lsrs r6, #2
wbulk_loop:
cmp r6, #0
beq wbulk_done
ldr r0, [r5]
bl ba_wdata
adds r5, #4
subs r6, #1
b wbulk_loop
wbulk_done:
pop {r4-r7,pc}
.ltorg

/* ---------- ba_rd_bulk: r0 = offset, r1 = dst, r2 = len (mult of 4).
 * ---------- */
.thumb_func
ba_rd_bulk:
push {r4-r7,lr}
mov r4, r0
mov r5, r1
mov r6, r2
lsls r0, r4, #11
ldr r1, =0x50000000
orrs r0, r1
orrs r0, r6
mov r7, r0
bl ba_pio_wr_pre
mov r0, r7
bl ba_cmd
ldr r4, =50000
rdbulk_poll:
ldr r0, =PIO0_FSTAT
ldr r2, [r0]
ldr r0, =0x100
tst r2, r0
beq rdbulk_got
subs r4, #1
bne rdbulk_poll
b rdbulk_done
rdbulk_got:
ldr r0, =PIO0_RXF0
ldr r2, [r0]
ldr r2, [r0]
ldr r2, [r0]
ldr r2, [r0]
mov r1, r2
lsrs r6, #2
rdbulk_loop:
cmp r6, #0
beq rdbulk_done
ldr r0, =PIO0_RXF0
ldr r2, [r0]
mov r0, r2
bl ba_bswap
str r0, [r5]
adds r5, #4
subs r6, #1
b rdbulk_loop
rdbulk_done:
pop {r4-r7,pc}
.ltorg

/* ---------- ba_hci: r0 = opcode, r1 = params, r2 = plen.
 * Builds H2B packet at TXBUF, bulk-writes at H2B_IN, bumps H2B_IN.
 * ---------- */
.thumb_func
ba_hci:
push {r4-r7,lr}
mov r4, r0
mov r5, r1
mov r6, r2
ldr r7, =TXBUF
mov r0, r6
adds r0, #3
strb r0, [r7, #0]
lsrs r0, #8
strb r0, [r7, #1]
movs r0, #0
strb r0, [r7, #2]
movs r0, #1
strb r0, [r7, #3]
mov r0, r4
strb r0, [r7, #4]
lsrs r0, #8
strb r0, [r7, #5]
mov r0, r6
strb r0, [r7, #6]
mov r2, r5
mov r3, r7
adds r3, #7
mov r1, r6
hci_copy:
cmp r1, #0
beq hci_pad
ldrb r0, [r2]
strb r0, [r3]
adds r2, #1
adds r3, #1
subs r1, #1
b hci_copy
hci_pad:
mov r0, r6
adds r0, #7
adds r0, #3
lsrs r0, #2
lsls r0, #2
mov r4, r0
mov r0, r6
adds r0, #7
subs r0, r4, r0
mov r1, r0
hci_padloop:
cmp r1, #0
beq hci_send
movs r0, #0
strb r0, [r3]
adds r3, #1
subs r1, #1
b hci_padloop
hci_send:
ldr r0, =STATE_H2B
ldr r0, [r0]
ldr r1, =TXBUF
mov r2, r4
bl ba_wr_bulk
ldr r0, =STATE_H2B
ldr r1, [r0]
adds r1, r4
ldr r2, =0xFFF
ands r1, r2
str r1, [r0]
ldr r0, =0x2000
bl ba_wr32
pop {r4-r7,pc}
.ltorg

/* ---------- ba_poll_b2h: -> r0 = bytes avail. ---------- */
.thumb_func
ba_poll_b2h:
push {r4-r5,lr}
ldr r0, =0x2008
bl ba_rd32
ldr r1, =0xFFF
ands r0, r1
ldr r1, =STATE_B2H
ldr r2, [r1]
subs r0, r2
pop {r4-r5,pc}
.ltorg

/* ---------- ba_read_ev: read one B2H event into RXBUF, bump B2H_OUT.
 * Clobbers r0-r3 via callees; uses r4-r7 (saved). ---------- */
.thumb_func
ba_read_ev:
push {r4-r7,lr}
ldr r4, =STATE_B2H
ldr r4, [r4]
ldr r0, =0x1000
orrs r0, r4
ldr r1, =RXBUF
movs r2, #4
bl ba_rd_bulk
ldr r0, =RXBUF
ldrh r1, [r0]
mov r4, r1
adds r4, #3
lsrs r4, #2
lsls r4, #2
ldr r0, =STATE_B2H
ldr r5, [r0]
adds r5, #4
ldr r6, =0x1000
orrs r5, r6
ldr r1, =RXBUF
mov r0, r5
mov r2, r4
bl ba_rd_bulk
ldr r0, =STATE_B2H
ldr r1, [r0]
adds r1, r4
adds r1, #4
ldr r2, =0xFFF
ands r1, r2
mov r5, r1
str r5, [r0]
ldr r0, =0x200C
mov r1, r5
bl ba_wr32
pop {r4-r7,pc}
.ltorg

/* ---------- ba_wait_cc: -> r0 = 0 ok / 1 timeout-or-bad. ---------- */
.thumb_func
ba_wait_cc:
push {r4-r5,lr}
ldr r4, =200000
wcc_poll:
bl ba_poll_b2h
cmp r0, #0
bne wcc_got
subs r4, #1
bne wcc_poll
movs r0, #1
pop {r4-r5,pc}
wcc_got:
bl ba_read_ev
ldr r0, =RXBUF
ldrb r1, [r0]
cmp r1, #14
bne wcc_bad
adds r0, #5
ldrb r1, [r0]
cmp r1, #0
bne wcc_bad
movs r0, #0
pop {r4-r5,pc}
wcc_bad:
movs r0, #1
pop {r4-r5,pc}
.ltorg

/* ---------- print helpers ---------- */
.thumb_func
print_string:
push {r1-r3,lr}
mov r1, r0
ldr r2, =UART0_DR
ps_loop:
ldrb r3, [r1]
cmp r3, #0
beq ps_done
str r3, [r2]
adds r1, #1
b ps_loop
ps_done:
pop {r1-r3,pc}
.ltorg

.thumb_func
print_hex32:
push {r1-r3,lr}
mov r1, r0
movs r2, #8
hex_digit:
lsrs r0, r1, #28
cmp r0, #10
blo hex_out
adds r0, #7
hex_out:
adds r0, #0x30
ldr r3, =UART0_DR
str r0, [r3]
lsls r1, #4
subs r2, #1
bne hex_digit
movs r0, #10
str r0, [r3]
pop {r1-r3,pc}
.ltorg

.section .rodata
.align 2
msg_start: .asciz "ARM BLE Starting (BT shared bus via PIO0)\n"
msg_btctrl: .asciz "ARM BLE BT-CTRL "
msg_rambase: .asciz "ARM BLE RAM-BASE "
msg_hostready: .asciz "ARM BLE HOST-READY\n"
msg_resetok: .asciz "ARM BLE RESET-OK\n"
msg_advok: .asciz "ARM BLE ADV-OK\n"
msg_listen: .asciz "ARM BLE LISTEN\n"
msg_scanok: .asciz "ARM BLE SCAN-OK\n"
msg_scantimeout: .asciz "ARM BLE SCAN-TIMEOUT\n"
msg_ccfail: .asciz "ARM BLE CC-FAIL\n"
blob_adv_params:  /* 16B stored, plen 15 */
    .byte 0x40, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    .byte 0x00, 0x07, 0x00, 0x00
blob_adv_data:  /* 32B: flags + BARM */
    .byte 0x0A, 0x02, 0x01, 0x06, 0x06, 0x09, 0x42, 0x41, 0x52, 0x4D, 0x00, 0x00
    .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
blob_adv_en:  /* 1B */
    .byte 0x01
blob_scan_params:  /* 8B stored, plen 7 */
    .byte 0x01, 0x10, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00
blob_scan_en:  /* 4B stored, plen 2 */
    .byte 0x01, 0x00, 0x00, 0x00
"""


def main():
    open(os.path.join(D, "ble_adv.S"), "w").write(ARM_SRC)
    print("wrote", os.path.join(D, "ble_adv.S"))


if __name__ == "__main__":
    main()
