#!/usr/bin/env python3
"""Generate eth_dhcp guest firmware: full ioLibrary-style DHCP client over
W5500 MACRAW socket 0 (single-gateway path), for M0+ / M33 / RV32.

Generates:
  test-firmware/eth_dhcp.S      ARM (RP2040 ifdefs; M0+ v6m-safe / M33)
  test-firmware/eth_dhcp_rv32.S RV32 (gen_rv32.py Demo style, rvlink.py)

Flow (identical on all chips, only addresses differ):
  1. UART init, print "ETH DHCP-START"
  2. SPI0 init (CR0=7 8-bit Motorola, CPSR=2, CR1=SSE)
  3. GPIO17 OE (CSn output), CS high idle
  4. VERSIONR read (expect 0x04) else "ETH FAIL VERSION"
  5. Sn_MR=MACRAW, OPEN sock0, expect SR=0x42 else "ETH FAIL OPEN"
  6. Build DHCP DISCOVER (xid per arch), write TX buf, TX_WR=len, SEND
  7. Poll RX_RSR + Sn_IR RECV (bounded) else "ETH FAIL OFFER-TIMEOUT"
  8. Read RX buffer, parse OFFER yiaddr, print "ETH OFFER IP=<a.b.c.d>"
  9. Build DHCP REQUEST (req IP = offered), SEND, poll ACK
  10. Parse ACK yiaddr, print "ETH IP=<a.b.c.d>", "ETH DONE"
  Failures print "ETH FAIL <reason>" (sweep greps ETH DONE).

Frame layout (all multi-byte fields big-endian on the wire):
  ETH: dst(6) src=SHAR(6) type 0800 | IPv4 | UDP | BOOTP/DHCP
  BOOTP: op=1 htype=1 hlen=6 hops=0 | xid(4) | secs=0 flags=0x8000 |
         ciaddr=0 yiaddr=0 siaddr=0 giaddr=0 | chaddr=SHAR+10 zero |
         sname(64) file(128) zero | magic 63,82,53,63 | opts | end 0xFF
  DISCOVER opts: 53,1,1 | 55,1,1(subnet) 55,1,3(router) 55,1,6(dns) |
                 12 hostname "pico-eth" | end
  REQUEST opts: 53,1,3 | 50,4,req_ip | 54,4,server_ip | end
  OFFER/ACK parse: yiaddr @bootp+16, msg type opt 53, server id opt 54.

Guest embeds DISCOVER/REQUEST as .byte blobs (from eth_dhcp_common.py) —
no guest-side checksums, no 300-byte runtime frame build. Parse side
stays byte-at-a-time against RXBUF (works on all arches).

W5500 SPI framing (VDM, CS bit-banged GPIO17):
  write: ah, al, (bsb<<3)|0x04, data...
  read:  ah, al, (bsb<<3)|0x00, 0xFF -> MISO
  sock0 regs BSB=1, TX buf BSB=2, RX buf BSB=3.
  MR=0x00 CR=0x01 IR=0x02 SR=0x03 TX_WR0=0x24 RSR0=0x26 RD0=0x28.
  MACRAW=0x04 OPEN=0x01 SEND=0x20 RECV=0x40. SR_MACRAW=0x42.
  IR RECV=0x04 SEND_OK=0x10 (W1C on write).
MACRAW RX layout: [len_hi,len_lo,frame...] per queued frame.

Per-arch constants:
  M0  (RP2040): UART0 0x40034000, SPI0 0x4003C000, RAM 0x20000000/264K
  M33 (RP2350): UART0 0x40070000, SPI0 0x40080000, RAM 0x20000000/520K
  RV32(RP2350): UART0 0x40070000, SPI0 0x40080000, RAM 0x20000000/520K
SIO base is 0xD0000000 on all three.
MAC: 02:11:22:33:44:5X (M0=0x60 M33=0x61 RV32=0x62).
XID: M0=A0.. M33=B0.. RV32=C0.. + fixed tail.

ARM codegen rules (M0+ Thumb-1 hard limits — the old hand .S died here):
  - NO ldr rX, =sym inside a function that also calls bl far away:
    the literal pool lands >1KB away (out of range fixup). Instead each
    function opens with a trampoline header: local literals + b body.
    Pattern:  b 1f | .ltorg-equivalent word block | 1: ... code ...
    Concretely: emit .word literals right after function entry branch,
    load via ldr [pc,#imm<1KB] — always in range since pool is adjacent.
  - Simpler rule used here: keep every function SMALL (<~200B) and put
    .ltorg after reset_handler and mid-file; ldr=addr pools stay close.
  - NO [Rn,#imm>31] byte ops, NO adds Rd,Rn,#imm>7: stepwise adds only.
  - NO high-reg arithmetic (adds r1,r4,#imm with r4>7 needs Thumb-2).
  - NO adcs/sbcs #imm.
  - bl range on v6m is +/-4MB: fine across the whole image.
RV32 codegen: gen_rv32.py Demo style (auipc string refs), linked by rvlink.py.

Run: python3 test-firmware/gen_eth_dhcp.py (writes eth_dhcp.S + eth_dhcp_rv32.S).
"""
import os
import sys

D = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, D)
from eth_dhcp_common import build_discover, build_request  # noqa: E402

# ---------------------------------------------------------------- arch table

ARCHES = {
    "m0": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x60]),
               xid=bytes([0xA0, 0xB0, 0xC0, 0xD0])),
    "m33": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x61]),
                xid=bytes([0xB0, 0xB1, 0xC0, 0xD1])),
    "rv32": dict(mac=bytes([0x02, 0x11, 0x22, 0x33, 0x44, 0x62]),
                 xid=bytes([0xC0, 0xB2, 0xC0, 0xD2])),
}

OFFER_IP = bytes([192, 168, 4, 2])
SERVER_IP = bytes([192, 168, 4, 1])


def blob_lines(blob, per_line=12):
    out = []
    for i in range(0, len(blob), per_line):
        chunk = blob[i:i + per_line]
        out.append("    .byte " + ", ".join(f"0x{b:02X}" for b in chunk))
    return "\n".join(out)


# ---------------------------------------------------------------- ARM source

ARM_TEMPLATE = r"""/*
 * eth_dhcp — full DHCP client over W5500 MACRAW socket 0.
 * Generated by gen_eth_dhcp.py - do not hand-edit (edit the generator).
 *
 * ioLibrary-style flow against the pico-eth board (W5500 on SPI0,
 * CSn=GPIO17 bit-banged, mode 0):
 *   OPEN/MACRAW sock0 -> SEND DHCP DISCOVER -> poll RECV -> parse OFFER
 *   -> SEND DHCP REQUEST -> poll ACK -> print ETH IP=a.b.c.d + ETH DONE.
 *
 * Two builds from this one source (RP2040 ifdefs):
 *   M0+   (RP2040): UART0 0x40034000 SPI0 0x4003C000 RAM_TOP 0x20042000
 *   M33   (RP2350): UART0 0x40070000 SPI0 0x40080000 RAM_TOP 0x20082000
 * Assemble M33 with -DRP2350 (build.sh _pico2 pattern, build_eth.py).
 *
 * Guest embeds DISCOVER/REQUEST as .byte blobs (checksums precomputed
 * in eth_dhcp_common.py) — no runtime frame build, no checksum code.
 * Parse side is byte-at-a-time against RXBUF (v6m-safe: no [Rn,#>31],
 * no adds>7, no high-reg arithmetic, no adcs-imm).
 *
 * Markers: ETH DHCP-START / ETH OFFER IP= / ETH IP= / ETH DONE / ETH FAIL.
__BLURB__
 */
.syntax unified
#ifdef RP2350
.cpu cortex-m33
#else
.cpu cortex-m0plus
#endif
.thumb

#ifdef RP2350
.equ UART0_DR,    0x40070000
.equ UART0_CR,    0x40070030
.equ RAM_TOP,     0x20082000
.equ SPI_CR0,     0x40080000
.equ SPI_CR1,     0x40080004
.equ SPI_DR,      0x40080008
.equ SPI_CPSR,    0x40080010
#else
.equ UART0_DR,    0x40034000
.equ UART0_CR,    0x40034030
.equ RAM_TOP,     0x20042000
.equ SPI_CR0,     0x4003C000
.equ SPI_CR1,     0x4003C004
.equ SPI_DR,      0x4003C008
.equ SPI_CPSR,    0x4003C010
#endif
.equ UART_CR_EN_LO, 0x01
.equ UART_CR_EN_HI, 0x03   /* UARTEN|TXE|RXE = 0x301, built v6m-safe */

.equ SIO_OE_SET,  0xD0000024
.equ SIO_OUT_SET, 0xD0000014
.equ SIO_OUT_CLR, 0xD0000018
/* CS mask as two 16-bit halves (v6m-safe): 0x20000 = HI 0x2 / LO 0x0000.
 * NEVER ldr r1, =CS_MASK (clang emits Thumb-2 mov.w for it); always
 * materialize via CS_MASK_HI/LO into SEPARATE low regs, then combine
 * with lsls+adds (both Thumb-1 legal). */
.equ CS_MASK_HI,  0x2
.equ CS_MASK_LO,  0x0000

/* W5500 socket-0 register offsets (BSB=1) */
.equ S_MR,   0x00
.equ S_CR,   0x01
.equ S_IR,   0x02
.equ S_SR,   0x03
.equ S_TXWR, 0x24
.equ S_RSR,  0x26
.equ S_RD,   0x28
.equ BSB_REG, 1
.equ BSB_TX,  2
.equ BSB_RX,  3

/* SRAM scratch (high addresses below the M0 RAM top so BOTH arches fit:
 * M0 SRAM is 0x20000000-0x20042000, M33 extends to 0x20082000; the stack
 * starts at RAM_TOP and grows down, TXBUF/RXBUF sit 1KB below M0 top). */
.equ TXBUF, 0x20041C00     /* 512B frame build area */
.equ RXBUF, 0x20041E00     /* 512B RX frame area */
.equ SAVE_SLOT, 0x20001000 /* MISO ground-truth word (see spi_xfer note) */

.section .vectors, "a", %progbits
.align 2
_vectors:
.word RAM_TOP
.word reset_handler
.word 0xFFFFFFFF
.word 0xFFFFFFFF
.rept 12
.word 0xFFFFFFFF
.endr

.section .text
.align 2

/* reset_handler is deliberately SMALL: init + VERSIONR/MACRAW-OPEN only,
 * then calls helpers. Its literal pool stays adjacent (.ltorg right
 * after failhalt), so no out-of-range ldr fixups on v6m. */
.thumb_func
.global reset_handler
reset_handler:
ldr r7, =RAM_TOP; mov sp, r7
ldr r4, =UART0_CR; movs r5, #UART_CR_EN_HI; lsls r5, r5, #8; adds r5, #UART_CR_EN_LO; str r5, [r4]
ldr r0, =msg_start; bl print_string
/* SPI0 init: CR0=7 (8-bit SPI), CPSR=2, CR1=SSE(2) */
ldr r0, =SPI_CR0; movs r1, #7; str r1, [r0]
ldr r0, =SPI_CPSR; movs r1, #2; str r1, [r0]
ldr r0, =SPI_CR1; movs r1, #2; str r1, [r0]
/* GPIO17 output, CS high idle */
ldr r0, =SIO_OE_SET; movs r1, #CS_MASK_HI; lsls r1, r1, #16; str r1, [r0]
ldr r0, =SIO_OUT_SET; movs r1, #CS_MASK_HI; lsls r1, r1, #16; str r1, [r0]
/* VERSIONR expect 0x04. NOTE: every SSPDR write clocks one byte and the
 * matching MISO byte must be DRAINED (SSPDR read) before the next write
 * — the RX FIFO holds only 8 and stale echoes misalign the frame. This
 * mirrors test_board_eth_attach_spi0_cs17 exactly. */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #0x39; bl spi_xfer_drain
movs r0, #0; bl spi_xfer_drain
movs r0, #0xFF; bl spi_xfer
bl spi_cs_hi
ldr r0, =SAVE_SLOT
ldr r4, [r0]
cmp r4, #4
beq ver_ok
ldr r0, =msg_fail_ver; bl print_string; b fail
ver_ok:
/* SHAR0..5 = frame SRC MAC (per-arch, selected by the same RP2350
 * ifdef as the blobs below): the vnet MACRAW attach + RX filter use
 * SHAR, and the server keys the lease off chaddr. Default SHAR
 * (02:00:..:01) matches neither, so OFFERs never arrive.
 * v6m-safe: r4=cursor, r5=SHAR addr 9..14, r6=data byte. spi_xfer_drain
 * preserves r0-r2 only (r3 is trash) — keep the byte in r6 (callee-saved,
 * and wait_offer's caller dhcp_run already saves r4-r7). */
/* SHAR is written with the W5500-word helper (wreg): one CS frame per
 * byte would also work, but wreg keeps addr+bsb+data in a single frame
 * exactly like the OPEN sequence below (proven path). r0=addr r1=bsb
 * r2=val. wreg preserves r4-r7 (push {r0-r3,lr} + inner push/pop). */
#ifdef RP2350
ldr r4, =mac_addr_m33
#else
ldr r4, =mac_addr_m0
#endif
movs r5, #9                 /* SHAR0 addr */
shar_loop:
ldrb r6, [r4]              /* val -> r6 (callee-saved, survives bl) */
push {r4-r5}               /* cursor+addr survive the call */
mov r0, r5                 /* addr -> r0 (wreg_shar_byte arg) */
bl wreg_shar_byte
pop {r4-r5}
adds r4, #1
adds r5, #1
cmp r5, #15
bne shar_loop
b shar_done
wreg_shar_byte:
/* r0 = SHAR addr (9..14). MAC byte arrives in r6 (caller's, preserved:
 * this function only touches r0-r3 + lr). */
push {r1-r3,lr}
mov r3, r6                /* data byte -> r3 */
mov r2, r0                /* addr lo -> r2 */
movs r0, #0               /* addr hi = 0 */
push {r2-r3}              /* save addr lo + data (r0-r1 free) */
bl spi_cs_lo
pop {r2-r3}
movs r0, #0; bl spi_xfer_drain       /* addr hi */
mov r0, r2; bl spi_xfer_drain        /* addr lo */
movs r0, #(0<<3)|4; bl spi_xfer_drain /* common-block write */
mov r0, r3; bl spi_xfer_drain        /* MAC byte */
bl spi_cs_hi
pop {r1-r3,pc}
shar_done:
/* Sn_MR = MACRAW(4), Sn_CR = OPEN(1), expect Sn_SR = 0x42.
 * Write-phase echoes are drained (bl spi_xfer_drain); only the final
 * data-phase MISO byte is kept. */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_MR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3)|4; bl spi_xfer_drain
movs r0, #4; bl spi_xfer_drain
bl spi_cs_hi
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_CR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3)|4; bl spi_xfer_drain
movs r0, #1; bl spi_xfer_drain
bl spi_cs_hi
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_SR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3); bl spi_xfer_drain
movs r0, #0xFF; bl spi_xfer
bl spi_cs_hi
ldr r0, =SAVE_SLOT
ldr r4, [r0]
cmp r4, #0x42
beq open_ok
ldr r0, =msg_fail_open; bl print_string; b fail
open_ok:
ldr r0, =msg_macraw; bl print_string
/* DHCP DORA lives in dhcp_run (own pool, own small literals) */
bl dhcp_run
halt: b halt
fail:
ldr r0, =msg_fail; bl print_string
failhalt: b failhalt
.ltorg

/* ---------- SPI byte exchange: r0=MOSI -> r0=MISO (low byte) ----------
 * spi_xfer keeps the MISO byte. spi_xfer_drain discards it (write phases:
 * without draining, the 8-deep RX FIFO fills and echoes misalign every
 * subsequent frame — the classic silent W5500 failure). */
.thumb_func
spi_xfer:
push {r1-r2,lr}
ldr r1, =SPI_DR
str r0, [r1]
ldr r0, [r1]
uxtb r0, r0
/* The data-phase MISO byte must ALSO survive in SRAM: high regs (r4+)
 * are observed to lose their value across later bl calls on this core
 * (print_hex8+print_string clobber r4 even though both preserve it —
 * root cause still open; SRAM is ground truth). spi_xfer itself only
 * touches r1-r2 (both restored), so wait_offer's mov r6,r0 pattern and
 * dhcp_run's arithmetic on r4-r7 stay intact. */
ldr r1, =SAVE_SLOT
str r0, [r1]
pop {r1,r2,pc}
.thumb_func
spi_xfer_drain:
/* Drain-only: preserves r0-r7 (headers live in r0-r3 AND r5-r6 across
 * phases: SHAR loop cursor/addr/data are r4-r6, TX_WR hi/lo are r2/r5,
 * wreg/rreg stash across push{p...} too). MISO is discarded into r1,
 * which is restored by the balanced pop — the push/pop register lists
 * MUST match (an old push{r1,lr}/pop{r1,pc} mismatch leaked one word
 * per call, walking SP down into the frame and crashing after VER-OK). */
push {r1,r2,lr}
ldr r1, =SPI_DR
str r0, [r1]
ldr r2, [r1]              /* MISO -> r2 (restored below, value dropped) */
pop {r1,r2,pc}
/* NOTE: r0 (MOSI) is dead after the call by convention; every other
 * register is preserved, including lr (returned via pc). */

/* ---------- CS helpers ---------- */
.thumb_func
spi_cs_lo:
push {r0,r1,lr}
ldr r0, =SIO_OUT_CLR; movs r1, #CS_MASK_HI; lsls r1, r1, #16; str r1, [r0]
pop {r0,r1,pc}
.thumb_func
spi_cs_hi:
push {r0,r1,lr}
ldr r0, =SIO_OUT_SET; movs r1, #CS_MASK_HI; lsls r1, r1, #16; str r1, [r0]
pop {r0,r1,pc}

/* ---------- W5500 reg write: r0=addr r1=bsb r2=val ----------
 * NOTE: wreg/rreg are DEAD CODE (kept for documentation; nothing bl's
 * to them — all live paths use inline drain sequences). They are still
 * assembled, so they must stay v6m-legal, but they are never called. */
.thumb_func
wreg:
push {r0-r3,lr}
mov r3, r2
lsrs r2, r0, #8           /* addr hi */
push {r0-r3}
mov r0, r2; bl spi_xfer
pop {r0-r3}
push {r0-r3}
mov r0, r0; bl spi_xfer  /* addr lo */
pop {r0-r3}
lsls r1, r1, #3
adds r1, #4
push {r0-r3}
mov r0, r1; bl spi_xfer
pop {r0-r3}
mov r0, r3; bl spi_xfer
pop {r0-r3,pc}

/* ---------- W5500 reg read: r0=addr r1=bsb -> r0=val (DEAD, see above) */
.thumb_func
rreg:
push {r1-r3,lr}
mov r3, r0
lsrs r2, r3, #8
push {r1-r3}
bl spi_cs_lo
mov r0, r2; bl spi_xfer_drain
mov r0, r3; bl spi_xfer_drain  /* lo byte */
pop {r1-r3}
lsls r1, r1, #3
push {r1-r3}
mov r0, r1; bl spi_xfer_drain
movs r0, #0xFF; bl spi_xfer
mov r3, r0
bl spi_cs_hi
mov r0, r3
pop {r1-r3,pc}

/* ---------- macraw_send: r0=buf r1=len_lo r2=len_hi ----------
 * Copies r1+r2*256 bytes to TX buf (VDM BSB_TX from addr 0), sets
 * TX_WR=len, issues SEND. Small loop, small pool. */
.thumb_func
macraw_send:
push {r4-r7,lr}
mov r4, r0                /* buf */
mov r5, r1                /* len lo */
mov r6, r2                /* len hi */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #0; bl spi_xfer_drain
movs r0, #(BSB_TX<<3)|4; bl spi_xfer_drain
/* Total = hi<<8|lo in r4 (v6m-safe lsls+adds); single down-counter in
 * r6. The old dual-counter loop never decremented hi and exited when
 * i-lo exceeded len-lo — copying 87B of a 342B frame. r5/r6 keep
 * len-lo/hi for the TX_WR writes below. */
mov r7, r4                /* cursor = buf */
lsls r4, r2, #8           /* hi<<8 (r2 = len-hi, still intact) */
adds r4, r4, r1           /* total = hi<<8|lo */
mov r6, r4                /* remaining */
txloop:
cmp r6, #0
beq txdone
ldrb r0, [r7]
bl spi_xfer_drain         /* TX echoes fill RX FIFO: drain (MISO unneeded) */
adds r7, #1
subs r6, #1
b txloop
txdone:
bl spi_cs_hi
/* TX_WR = len BE (two single-byte reg writes; TX_WR0 is the HIGH byte).
 * SINGLE CS FRAME for both bytes: the W5500 TX_WR is a 16-bit pointer
 * and the model latches each byte write independently — but splitting
 * hi/lo across two CS frames lets a stale-data echo from the first
 * frame's data phase bleed into the second frame's header on the
 * 8-deep PL022 FIFO if any drain is missed. One frame = one addr
 * phase (VDM auto-increment 0x24->0x25), two data bytes, no gap. */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_TXWR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3)|4; bl spi_xfer_drain
mov r0, r2; bl spi_xfer_drain        /* hi byte -> 0x24 */
mov r0, r5; bl spi_xfer_drain        /* lo -> 0x25 */
bl spi_cs_hi
/* Sn_CR = SEND (SEND_OK observed via Sn_IR poll; data-phase MISO
 * unneeded — drain to keep the RX FIFO aligned). */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_CR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3)|4; bl spi_xfer_drain
movs r0, #0x20; bl spi_xfer_drain
bl spi_cs_hi
pop {r4-r7,pc}

/* ---------- dhcp_run: DISCOVER->OFFER->REQUEST->ACK, prints, DONE ----------
 * Own literal pool (blobs + strings are all nearby). Frame bytes come
 * from the .rodata blobs; REQUEST is patched with offered yiaddr+server
 * before send (copy_blob helper). */
.thumb_func
dhcp_run:
push {r4-r7,lr}
/* SEND DISCOVER blob */
ldr r0, =TXBUF
ldr r1, =disc_blob
movs r2, #(__DISC_LEN_LO__)
movs r3, #(__DISC_LEN_HI__)
bl copy_blob
ldr r0, =TXBUF
movs r1, #(__DISC_LEN_LO__)
movs r2, #(__DISC_LEN_HI__)
bl macraw_send
/* await OFFER (msg type 2) */
bl wait_offer
cmp r0, #2
beq d_got_offer
ldr r0, =msg_fail_offer; bl print_string; b dhcp_fail
d_got_offer:
ldr r0, =msg_offer; bl print_string
bl print_ip
ldr r0, =msg_nl; bl print_string
/* SEND REQUEST blob (patched with yip/sip by wait_offer) */
ldr r0, =TXBUF
ldr r1, =req_blob
movs r2, #(__REQ_LEN_LO__)
movs r3, #(__REQ_LEN_HI__)
bl copy_blob
bl patch_request
ldr r0, =TXBUF
movs r1, #(__REQ_LEN_LO__)
movs r2, #(__REQ_LEN_HI__)
bl macraw_send
/* await ACK (msg type 5) */
bl wait_offer
cmp r0, #5
beq d_got_ack
ldr r0, =msg_fail_ack; bl print_string; b dhcp_fail
d_got_ack:
ldr r0, =msg_ip; bl print_string
bl print_ip
ldr r0, =msg_nl; bl print_string
ldr r0, =msg_done; bl print_string
pop {r4-r7,pc}
dhcp_fail:
ldr r0, =msg_fail; bl print_string
pop {r4-r7,pc}
.ltorg

/* ---------- copy_blob: r0=dst r1=src r2=len_lo r3=len_hi ----------
 * v6m-safe: build total = hi<<8|lo in r3, single down-counter in r2.
 * (The old dual-counter form decremented lo but ADDED on wrap, so the
 * 342B DISCOVER spun forever: lo wraps every 86/87 bytes, hi grows
 *  without bound and the loop never exits.) */
.thumb_func
copy_blob:
push {r4-r6,lr}
mov r4, r0
mov r5, r1
lsls r3, r3, #8             /* hi<<8 */
adds r3, r3, r2             /* total = hi<<8|lo */
mov r2, r3                  /* remaining */
cbloop:
cmp r2, #0
beq cbdone
ldrb r3, [r5]
strb r3, [r4]
adds r4, #1
adds r5, #1
subs r2, #1
b cbloop
cbdone:
pop {r4-r6,pc}

/* ---------- patch_request: TXBUF REQUEST gets yip@opt50, sip@opt54 -----
 * REQUEST blob layout: opts start at TXBUF+14+20+8+240 = TXBUF+282.
 * opt53(3B) then opt50(6B: 50,4,a.b.c.d) then opt54(6B: 54,4,a.b.c.d).
 * Requested-IP value = TXBUF+282+3+2 = TXBUF+287; server value =
 * TXBUF+282+3+6+2 = TXBUF+293. Reached by small stepwise adds (v6m). */
.thumb_func
patch_request:
push {r0-r3,lr}
/* r0 = TXBUF+287 (requested-IP value) via 41x7 */
ldr r0, =TXBUF
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7               /* +287 */
ldr r1, =yip_addr
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
adds r0, #2               /* TXBUF+293 = server-IP value (+6) */
ldr r1, =sip_addr
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
adds r0, #1
adds r1, #1
ldrb r2, [r1]; strb r2, [r0]
pop {r0-r3,pc}
.ltorg

/* ---------- wait_offer: poll RECV, parse msg type -> r0 (2/5/0) -------
 * Bounded poll of Sn_IR RECV; reads one RX frame (len prefix + frame)
 * into RXBUF; validates ethertype/bootp magic/xid; saves yiaddr+server;
 * returns DHCP msg type (opt 53) or 0 on timeout/mismatch (then the
 * caller retries until its own bound expires).
 * NOTE: Sn_IR is polled WITHOUT dropping CS between header bytes and
 * the data byte (single CS frame; CS-hi between header/data would still
 * work on VDM but wastes polls). r6 holds the RECV bit in r0-safe regs
 * (r0 dies in spi_xfer_drain — MISO returns in r0 only from spi_xfer). */
.thumb_func
wait_offer:
push {r4-r7,lr}
ldr r5, =0x2000000           /* outer bound (~33M iters) */
wo_poll:
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_IR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3); bl spi_xfer_drain
movs r0, #0xFF; bl spi_xfer
mov r6, r0
bl spi_cs_hi
mov r0, r6
movs r1, #4
ands r0, r1
bne wo_got
subs r5, #1
bne wo_poll
movs r0, #0
pop {r4-r7,pc}
wo_got:
/* read RX buffer start: len_hi,len_lo then frame bytes to RXBUF.
 * Header-phase echoes drained; len bytes KEPT (need them); frame bytes
 * KEPT (strb to RXBUF). */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #0; bl spi_xfer_drain
movs r0, #(BSB_RX<<3); bl spi_xfer_drain
movs r0, #0xFF; bl spi_xfer
mov r6, r0                /* len hi */
movs r0, #0xFF; bl spi_xfer
mov r7, r0                /* len lo */
lsls r6, r6, #8
adds r6, r6, r7           /* r6 = frame len */
ldr r4, =RXBUF
mov r5, r6
wo_rxcopy:
cmp r5, #0
beq wo_rxdone
movs r0, #0xFF; bl spi_xfer
strb r0, [r4]               /* KEEP MISO: model returns data, not echo */
adds r4, #1
subs r5, #1
b wo_rxcopy
wo_rxdone:
bl spi_cs_hi
/* Sn_CR = RECV (consume one frame; data-phase MISO unneeded — drain) */
bl spi_cs_lo
movs r0, #0; bl spi_xfer_drain
movs r0, #S_CR; bl spi_xfer_drain
movs r0, #(BSB_REG<<3)|4; bl spi_xfer_drain
movs r0, #0x40; bl spi_xfer_drain
bl spi_cs_hi
bl parse_offer            /* r0 = msg type or 0 */
cmp r0, #0
bne wo_done
/* not ours: re-poll budget (v6m-safe, no T2 mov.w) then give up */
ldr r5, =0x1000000           /* re-poll budget */
b wo_poll
wo_done:
pop {r4-r7,pc}
.ltorg

/* ---------- parse_offer: RXBUF frame -> yiaddr/sip, r0 = msgtype/0 ----
 * Checks ethertype 0800, bootp magic, xid; saves yiaddr->yip_addr and
 * opt54->sip_addr; walks options for opt53. Byte-at-a-time, v6m-safe. */
.thumb_func
parse_offer:
push {r4-r7,lr}
ldr r0, =RXBUF
adds r0, #7
adds r0, #5               /* r0 = RXBUF+12 ethertype */
ldrb r1, [r0]
cmp r1, #8
bne po_no
adds r0, #1
ldrb r1, [r0]
cmp r1, #0
bne po_no
adds r0, #1               /* r0 = RXBUF+14 IP */
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #2
adds r0, #2               /* r0 = bootp+4 xid */
ldrb r1, [r0]
cmp r1, #__XID0__
bne po_no
adds r0, #1
ldrb r1, [r0]
cmp r1, #__XID1__
bne po_no
adds r0, #7
adds r0, #4               /* r0 = bootp+16 yiaddr */
ldr r1, =yip_addr
ldrb r2, [r0]; strb r2, [r1]
adds r0, #1
adds r1, #1
ldrb r2, [r0]; strb r2, [r1]
adds r0, #1
adds r1, #1
ldrb r2, [r0]; strb r2, [r1]
adds r0, #1
adds r1, #1
ldrb r2, [r0]; strb r2, [r1]
/* r0 = bootp+19 -> magic at bootp+236 (+217) */
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7
adds r0, #7               /* +217 = bootp+236 */
ldrb r1, [r0]
cmp r1, #99
bne po_no
adds r0, #1
ldrb r1, [r0]
cmp r1, #130
bne po_no
adds r0, #3               /* bootp+240 options */
ldr r1, =sip_addr
movs r2, #0               /* msg type */
po_optloop:
ldrb r3, [r0]
cmp r3, #255
beq po_optdone
cmp r3, #53
bne po_opt_next
adds r0, #2
ldrb r2, [r0]
subs r0, #2
b po_opt_adv
po_opt_next:
cmp r3, #54
bne po_opt_adv
adds r0, #2
ldrb r3, [r0]; strb r3, [r1]
adds r0, #1
adds r1, #1
ldrb r3, [r0]; strb r3, [r1]
adds r0, #1
adds r1, #1
ldrb r3, [r0]; strb r3, [r1]
adds r0, #1
adds r1, #1
ldrb r3, [r0]; strb r3, [r1]
subs r0, #3
subs r1, #3
b po_opt_adv2
po_opt_adv:
ldrb r3, [r0, #1]
adds r0, #2
adds r0, r0, r3
b po_optloop
po_opt_adv2:
ldrb r3, [r0, #1]
adds r0, #2
adds r0, r0, r3
b po_optloop
po_optdone:
mov r0, r2
pop {r4-r7,pc}
po_no:
movs r0, #0
pop {r4-r7,pc}
.ltorg

/* print_hex8: r0 = byte -> 2 hex digits. Lives with the other print
 * helpers (pool-local); the early .ltorg after reset covers reset's own
 * literals. Clobbers r1,r2. */
.thumb_func
print_hex8:
push {r1,r2,lr}
mov r1, r0
lsrs r0, r1, #4
cmp r0, #10
blo hex8_hi
adds r0, #7
hex8_hi:
adds r0, #0x30
ldr r2, =UART0_DR
str r0, [r2]
movs r0, r1
movs r1, #15
ands r0, r1
cmp r0, #10
blo hex8_lo
adds r0, #7
hex8_lo:
adds r0, #0x30
str r0, [r2]
pop {r1,r2,pc}

/* ---------- print helpers ---------- */
.thumb_func
print_string:
push {r1-r3,lr}
mov r1, r0
ldr r2, =UART0_DR
ps_loop:
ldrb r3, [r1]
cmp r3, #0
beq ps_done
str r3, [r2]
adds r1, #1
b ps_loop
ps_done:
pop {r1-r3,pc}

.thumb_func
print_ip:                 /* prints yip_addr as a.b.c.d (no newline) */
push {r4-r6,lr}
ldr r4, =yip_addr
movs r5, #4
ip_oct:
ldrb r0, [r4]
bl print_u8
subs r5, #1
beq ip_end
movs r0, #46              /* '.' */
ldr r1, =UART0_DR
str r0, [r1]
adds r4, #1
b ip_oct
ip_end:
pop {r4-r6,pc}

.thumb_func
print_u8:                 /* r0 = 0..255 -> decimal, no leading zeros */
push {r4-r6,lr}
mov r4, r0
movs r6, #0
movs r5, #100
bl print_digit
movs r5, #10
bl print_digit
movs r5, #1
bl print_digit
pop {r4-r6,pc}

.thumb_func
print_digit:              /* r4=val r5=div r6=printed-flag; digit via subtract */
push {r0-r2,lr}
mov r0, r4
mov r1, r5
movs r2, #0
dloop:
cmp r0, r1
blo ddone
subs r0, r0, r1
adds r2, #1
b dloop
ddone:
mov r4, r0
cmp r5, #1
beq dshow
cmp r2, #0
bne dshow
cmp r6, #1
beq dshow_zero
b dend
dshow_zero:
movs r2, #0
dshow:
adds r2, #48
ldr r0, =UART0_DR
str r2, [r0]
movs r6, #1
b dend
dend:
pop {r0-r2,pc}

.ltorg

.section .rodata
.align 2
msg_start: .asciz "ETH DHCP-START\n"
msg_macraw: .asciz "ETH MACRAW-OK\n"
msg_offer: .asciz "ETH OFFER IP="
msg_ip: .asciz "ETH IP="
msg_nl: .asciz "\n"
msg_done: .asciz "ETH DONE\n"
msg_fail: .asciz "ETH FAIL\n"
msg_fail_ver: .asciz "ETH FAIL VERSION\n"
msg_fail_open: .asciz "ETH FAIL OPEN\n"
msg_fail_offer: .asciz "ETH FAIL OFFER-TIMEOUT\n"
msg_fail_ack: .asciz "ETH FAIL ACK-TIMEOUT\n"
__DISC_BLOB__
__REQ_BLOB__
mac_addr: .byte __MAC__
ip_hdr: .byte 0x45,0,0,0, 0x11,0x22,0,0, 64,17,0,0, 0,0,0,0, 255,255,255,255

/* SRAM state (NOT .bss/.data: the raw .bin image has no startup copier
 * and flash is not writable — state lives at fixed SRAM addresses valid
 * on BOTH arches: M0 SRAM is 0x20000000-0x20042000, M33 0x20082000 top;
 * low 0x20000000+256 is free RAM on both; stack starts at RAM_TOP). */
.equ YIP_ADDR, 0x20000100
.equ SIP_ADDR, 0x20000104
.equ yip_addr, YIP_ADDR
.equ sip_addr, SIP_ADDR
"""

# ---------------------------------------------------------------- RV32 source

# NOTE (2026-09-15): an earlier draft of this file kept a dead RV32
# prologue template (RV_TEMPLATE/RV_PROLOGUE/RV_HELPERS) with unprefixed
# labels (spi_xfer, halt, fail, macraw_send...). gen_eth_dhcp.py emits
# ONE .S per arch, but the stale template still defined those symbols in
# the same file scope, so every bl resolved to the WRONG address and the
# guest wedged at 0x00000000. Deleted. The live RV32 emitter is
# rv32_source() below (rv_-prefixed helpers only).


def arm_source():
    blurb = (" * M0 MAC %s XID %s / M33 MAC %s XID %s." % (
        ":".join(f"{b:02X}" for b in ARCHES["m0"]["mac"]),
        ARCHES["m0"]["xid"].hex(), ":".join(f"{b:02X}" for b in ARCHES["m33"]["mac"]),
        ARCHES["m33"]["xid"].hex()))
    # One source, two builds: M0 vs M33 differ only in addresses (ifdef)
    # — but MAC/XID differ per arch, so emit BOTH blob sets, select
    # with #ifdef RP2350.
    out = []
    for tag, m, x in (("M0", ARCHES["m0"]["mac"], ARCHES["m0"]["xid"]),
                      ("M33", ARCHES["m33"]["mac"], ARCHES["m33"]["xid"])):
        d = build_discover(m, x)
        r = build_request(m, x, OFFER_IP, SERVER_IP)
        out.append((tag, d, r))
    lines = []
    for tag, d, r in out:
        sel = "#ifdef RP2350" if tag == "M33" else "#ifndef RP2350"
        lines.append(sel)
        lines.append(f"disc_blob:  /* {tag} DISCOVER {len(d)}B */")
        lines.append(blob_lines(d))
        lines.append(f"req_blob:   /* {tag} REQUEST {len(r)}B */")
        lines.append(blob_lines(r))
        lines.append("#endif")
    blobs = "\n".join(lines)
    src = ARM_TEMPLATE
    # lengths identical across arches (same layout)? Verify, then bake in.
    assert len(out[0][1]) == len(out[1][1]) and len(out[0][2]) == len(out[1][2]), \
        (len(out[0][1]), len(out[1][1]), len(out[0][2]), len(out[1][2]))
    # Frame lens are 342 (0x156): BOTH bytes must be backed in, because
    # movs can only carry 0..255 — (#(86)/#(1) here would truncate to 86B
    # and the gateway would see a runt DISCOVER with no magic/cookie).
    dd, dr = len(out[0][1]), len(out[0][2])
    assert dd == 342 and dr == 342, (dd, dr)
    src = src.replace("movs r2, #(__DISC_LEN_LO__)", f"movs r2, #({dd & 0xFF})")
    src = src.replace("movs r3, #(__DISC_LEN_HI__)", f"movs r3, #({(dd >> 8) & 0xFF})")
    src = src.replace("movs r1, #(__DISC_LEN_LO__)", f"movs r1, #({dd & 0xFF})")
    src = src.replace("movs r2, #(__DISC_LEN_HI__)", f"movs r2, #({(dd >> 8) & 0xFF})")
    src = src.replace("movs r2, #(__REQ_LEN_LO__)", f"movs r2, #({dr & 0xFF})")
    src = src.replace("movs r3, #(__REQ_LEN_HI__)", f"movs r3, #({(dr >> 8) & 0xFF})")
    src = src.replace("movs r1, #(__REQ_LEN_LO__)", f"movs r1, #({dr & 0xFF})")
    src = src.replace("movs r2, #(__REQ_LEN_HI__)", f"movs r2, #({(dr >> 8) & 0xFF})")
    # XID differs per arch: ifdef at the two compare sites
    src = src.replace("cmp r1, #__XID0__",
                      "#ifdef RP2350\ncmp r1, #0x%02X\n#else\ncmp r1, #0x%02X\n#endif"
                      % (ARCHES["m33"]["xid"][0], ARCHES["m0"]["xid"][0]))
    src = src.replace("cmp r1, #__XID1__",
                      "#ifdef RP2350\ncmp r1, #0x%02X\n#else\ncmp r1, #0x%02X\n#endif"
                      % (ARCHES["m33"]["xid"][1], ARCHES["m0"]["xid"][1]))
    mac_m0 = ",".join(f"0x{b:02X}" for b in ARCHES["m0"]["mac"])
    mac_m33 = ",".join(f"0x{b:02X}" for b in ARCHES["m33"]["mac"])
    # NOTE: NO `mac_addr = ...` alias — build_eth.py only handles ABS32
    # against section symbols; an .equ-to-symbol alias emits R_ARM_NONE
    # (silently unpatched -> pool slot 0 -> mac read from string bytes).
    # Both code sites use the RP2350 ifdef directly instead.
    src = src.replace("mac_addr: .byte __MAC__",
                      "mac_addr_m33: .byte " + mac_m33 +
                      "\nmac_addr_m0: .byte " + mac_m0)
    src = src.replace("__DISC_BLOB__\n__REQ_BLOB__", blobs)
    src = src.replace("__BLURB__", "\n" + blurb)
    return src


def main():
    arm = arm_source()
    open(os.path.join(D, "eth_dhcp.S"), "w").write(arm)
    print("wrote", os.path.join(D, "eth_dhcp.S"))
    # RV32 source is appended to gen_rv32.py DEMOS instead (keeps rvlink
    # flow identical); see gen function below.
    rv = rv32_source()
    open(os.path.join(D, "eth_dhcp_rv32.S"), "w").write(rv)
    print("wrote", os.path.join(D, "eth_dhcp_rv32.S"))


def rv32_source():
    # RV32 DHCP client: same SPI/CS flow, blob-based, Demo style
    # (auipc string refs) so rvlink.py links it like the other demos.
    # addi-immediate limit: blob lens must fit 12-bit signed (342/354 ok).
    mac = ARCHES["rv32"]["mac"]
    xid = ARCHES["rv32"]["xid"]
    disc = build_discover(mac, xid)
    req = build_request(mac, xid, OFFER_IP, SERVER_IP)
    assert len(disc) < 2048 and len(req) < 2048
    assert -2048 <= len(disc) <= 2047 and -2048 <= len(req) <= 2047, \
        (len(disc), len(req))
    L = []
    A = L.append
    A("/* ETH DHCP RV32 Test (RP2350 RISC-V, Hazard3 RV32IMAC).")
    A(" * Generated by gen_eth_dhcp.py - do not hand-edit (edit the generator).")
    A(" * Flash base 0x10000000 (entry via bootrom), SRAM to 0x20082000.")
    A(" */")
    A("    .text")
    A("    .globl _start")
    A("    .align 2")
    A("_start:")
    A("    lui sp, 0x20082            # SP = top of SRAM")
    A("    lui t0, 0x40070            # UART0 base")
    A("    addi t1, zero, 0x301")
    A("    sw t1, 0x30(t0)            # UARTEN|TXE|RXE")
    A(".Lr1: auipc a0, %pcrel_hi(.Ls1)")
    A("    addi a0, a0, %pcrel_lo(.Lr1)")
    A("    jal ra, rv_print_string")
    A("    lui t0, 0x40080            # SPI0 base")
    A("    addi t1, zero, 7")
    A("    sw t1, 0(t0)")
    A("    addi t1, zero, 2")
    A("    sw t1, 0x10(t0)")
    A("    sw t1, 0x04(t0)")
    A("    lui t0, 0xD0000")
    A("    addi t0, t0, 0x24          # SIO OE_SET")
    A("    lui t1, 0x20                # GPIO17 mask 0x20000")
    A("    sw t1, 0(t0)")
    A("    lui t0, 0xD0000")
    A("    addi t0, t0, 0x14          # SIO OUT_SET")
    A("    sw t1, 0(t0)")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x39")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    mv s0, a0")
    A("    jal ra, rv_spi_cs_hi")
    A("    addi t0, zero, 4")
    A("    bne s0, t0, rv_ver_fail")
    # SHAR must match the frame SRC MAC: vnet MACRAW attach + RX filter
    # use SHAR, and the DHCP server keys the lease off chaddr. Default
    # SHAR (02:00:..:01) matches neither the frame SRC (02:11:..:62) nor
    # chaddr, so OFFERs never arrive. Write SHAR0..5 = frame MAC.
    A("    jal ra, rv_spi_cs_lo          # SHAR0..5 = frame SRC MAC")
    for i, b in enumerate(mac):
        if i > 0:
            A("    jal ra, rv_spi_cs_hi")
            A("    jal ra, rv_spi_cs_lo")
        A("    addi a0, zero, 0")
        A("    jal ra, rv_spi_xfer")
        A(f"    addi a0, zero, {9 + i}         # SHAR{i}")
        A("    jal ra, rv_spi_xfer")
        A("    addi a0, zero, 0x04        # common write")
        A("    jal ra, rv_spi_xfer")
        A(f"    addi a0, zero, {b}         # MAC byte {i}")
        A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x0C")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 4")
    A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 1")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x0C")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 1")
    A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 3")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 8")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    mv s0, a0")
    A("    jal ra, rv_spi_cs_hi")
    A("    addi t0, zero, 0x42")
    A("    bne s0, t0, rv_open_fail")
    A(".Lr2: auipc a0, %pcrel_hi(.Ls2)")
    A("    addi a0, a0, %pcrel_lo(.Lr2)")
    A("    jal ra, rv_print_string")
    A("    jal ra, rv_dhcp_run")
    A("    j rv_halt")
    A("rv_ver_fail:")
    A(".Lr3: auipc a0, %pcrel_hi(.Ls3)")
    A("    addi a0, a0, %pcrel_lo(.Lr3)")
    A("    jal ra, rv_print_string")
    A("    j rv_fail")
    A("rv_open_fail:")
    A(".Lr4: auipc a0, %pcrel_hi(.Ls4)")
    A("    addi a0, a0, %pcrel_lo(.Lr4)")
    A("    jal ra, rv_print_string")
    A("    j rv_fail")
    A("rv_fail:")
    A(".Lr5: auipc a0, %pcrel_hi(.Ls5)")
    A("    addi a0, a0, %pcrel_lo(.Lr5)")
    A("    jal ra, rv_print_string")
    A("rv_halt:")
    A("    j rv_halt")
    A("rv_spi_xfer:")
    A("    addi sp, sp, -16")
    A("    sw ra, 12(sp)")
    A("    lui t0, 0x40080")
    A("    sw a0, 8(t0)")
    A("    lw a0, 8(t0)")
    A("    andi a0, a0, 0xFF")
    A("    lw ra, 12(sp)")
    A("    addi sp, sp, 16")
    A("    ret")
    A("rv_spi_cs_lo:")
    A("    addi sp, sp, -16")
    A("    sw ra, 12(sp)")
    A("    lui t0, 0xD0000")
    A("    addi t0, t0, 0x18          # SIO OUT_CLR (wreg-style: no sw-off)")
    A("    lui t1, 0x20")
    A("    sw t1, 0(t0)")
    A("    lw ra, 12(sp)")
    A("    addi sp, sp, 16")
    A("    ret")
    A("rv_spi_cs_hi:")
    A("    addi sp, sp, -16")
    A("    sw ra, 12(sp)")
    A("    lui t0, 0xD0000")
    A("    addi t0, t0, 0x14          # SIO OUT_SET (wreg-style)")
    A("    lui t1, 0x20")
    A("    sw t1, 0(t0)")
    A("    lw ra, 12(sp)")
    A("    addi sp, sp, 16")
    A("    ret")
    # --- dhcp_run: send DISCOVER blob, wait OFFER, send REQUEST, wait ACK
    # + rodata (strings, blobs) + print helpers, so rvlink lays out
    # .text @0x10000000, .rodata after — same as the other demos.
    A("rv_dhcp_run:")
    A("    addi sp, sp, -32")
    A("    sw ra, 28(sp)")
    A("    sw s0, 24(sp)")
    A("    sw s1, 20(sp)")
    A("    sw s2, 16(sp)")
    A(".Lr6: auipc a0, %pcrel_hi(disc_blob)")
    A("    addi a0, a0, %pcrel_lo(.Lr6)")
    A(f"    addi a1, zero, {len(disc)}")
    A("    jal ra, rv_macraw_send")
    A("    jal ra, rv_wait_offer          # a0 = msg type (2/5/0)")
    A("    addi t0, zero, 2")
    A("    bne a0, t0, rv_offer_fail")
    A(".Lr7: auipc a0, %pcrel_hi(.Ls6)")
    A("    addi a0, a0, %pcrel_lo(.Lr7)")
    A("    jal ra, rv_print_string")
    A("    jal ra, rv_print_ip")
    A(".Lr8: auipc a0, %pcrel_hi(.Ls8)")
    A("    addi a0, a0, %pcrel_lo(.Lr8)")
    A("    jal ra, rv_print_string")
    A(".Lr9: auipc a0, %pcrel_hi(req_blob)")
    A("    addi a0, a0, %pcrel_lo(.Lr9)")
    A("    jal ra, rv_patch_request      # a0 = TXBUF stamped copy")
    A(f"    addi a1, zero, {len(req)}")
    A("    jal ra, rv_macraw_send")
    A("    jal ra, rv_wait_offer")
    A("    addi t0, zero, 5")
    A("    bne a0, t0, rv_ack_fail")
    A(".Lr10: auipc a0, %pcrel_hi(.Ls7)")
    A("    addi a0, a0, %pcrel_lo(.Lr10)")
    A("    jal ra, rv_print_string")
    A("    jal ra, rv_print_ip")
    A(".Lr11: auipc a0, %pcrel_hi(.Ls8)")
    A("    addi a0, a0, %pcrel_lo(.Lr11)")
    A("    jal ra, rv_print_string")
    A(".Lr12: auipc a0, %pcrel_hi(.Ls9)")
    A("    addi a0, a0, %pcrel_lo(.Lr12)")
    A("    jal ra, rv_print_string")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    lw s1, 20(sp)")
    A("    lw s2, 16(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    A("rv_offer_fail:")
    A(".Lr13: auipc a0, %pcrel_hi(.Ls10)")
    A("    addi a0, a0, %pcrel_lo(.Lr13)")
    A("    jal ra, rv_print_string")
    A("    j rv_dhcp_fail_ret")
    A("rv_ack_fail:")
    A(".Lr14: auipc a0, %pcrel_hi(.Ls11)")
    A("    addi a0, a0, %pcrel_lo(.Lr14)")
    A("    jal ra, rv_print_string")
    A("rv_dhcp_fail_ret:")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    lw s1, 20(sp)")
    A("    lw s2, 16(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    # --- macraw_send: a0=src a1=len (len kept in s2 for TX_WR) ---
    A("rv_macraw_send:")
    A("    addi sp, sp, -32")
    A("    sw ra, 28(sp)")
    A("    sw s0, 24(sp)")
    A("    sw s1, 20(sp)")
    A("    sw s2, 16(sp)")
    A("    mv s0, a0")
    A("    mv s1, a1")
    A("    mv s2, a1                # s2 = len (TX_WR below)")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x14        # (BSB_TX<<3)|VDM-write: bsb=2,rw=1,om=0")
    A("    jal ra, rv_spi_xfer")
    A("rv_ms_loop:")
    A("    beqz s1, rv_ms_txwr")
    A("    lbu a0, 0(s0)")
    A("    jal ra, rv_spi_xfer")
    A("    addi s0, s0, 1")
    A("    addi s1, s1, -1")
    A("    j rv_ms_loop")
    A("rv_ms_txwr:")
    A("    jal ra, rv_spi_cs_hi")
    A("    # TX_WR hi+lo in ONE CS frame (VDM auto-increment 0x24->0x25).")
    A("    # Split hi/lo frames risk a stale-echo header on the 2nd frame.")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x24        # TX_WR0 = HIGH byte")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x0C")
    A("    jal ra, rv_spi_xfer")
    A("    srli a0, s2, 8             # hi DIRECT from s-reg (t-regs die in jal)")
    A("    jal ra, rv_spi_xfer")
    A("    andi a0, s2, 0xFF          # lo DIRECT from s-reg (VDM incr -> 0x25)")
    A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_spi_cs_lo          # Sn_CR = SEND")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 1")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x0C")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x20")
    A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    lw s1, 20(sp)")
    A("    lw s2, 16(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    # --- wait_offer: poll Sn_IR RECV, read 1 frame to RXBUF, parse ---
    # -> a0 = DHCP msg type (2 OFFER / 5 ACK) or 0 timeout/mismatch.
    A("rv_wait_offer:")
    A("    addi sp, sp, -32")
    A("    sw ra, 28(sp)")
    A("    sw s0, 24(sp)")
    A("    sw s1, 20(sp)")
    A("    sw s2, 16(sp)")
    A("    lui s2, 0x200              # bound = 0x2000000 poll iters")
    A("                               # (~33M: survives peer/bridge round-")
    A("                               # trip latency; 25k iters raced the")
    A("                               # python peer and always timed out).")
    A("rv_wo_poll:")
    A("    jal ra, rv_spi_cs_lo")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 2           # S_IR")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 8           # (1<<3)|0 read")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    andi s0, a0, 4            # s0: t0/t1 BOTH die in rv_spi_cs_hi")
    A("                              # (lui t0/sw + lui t1/sw); s0 is")
    A("                              # callee-saved (sw/lw in prologue).")
    A("    jal ra, rv_spi_cs_hi")
    A("    bnez s0, rv_wo_got")
    A("    addi s2, s2, -1")
    A("    bnez s2, rv_wo_poll")
    A("    addi a0, zero, 0")
    A("    j rv_wo_done")
    A("rv_wo_got:")
    A("    jal ra, rv_spi_cs_lo          # RX read from addr 0, BSB_RX")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x18        # (3<<3)|0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    mv s0, a0                  # len hi")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    mv s1, a0                  # len lo")
    A("    slli s0, s0, 8")
    A("    add s0, s0, s1             # s0 = frame len")
    A("    lui t0, 0x20042")
    A("    addi t0, t0, -0x200        # RXBUF 0x20041E00")
    A("    mv s1, t0                  # dst cursor")
    A("    mv s2, s0                  # remaining")
    A("rv_rx_copy:")
    A("    beqz s2, rv_rx_done")
    A("    addi a0, zero, 0xFF")
    A("    jal ra, rv_spi_xfer")
    A("    sb a0, 0(s1)")
    A("    addi s1, s1, 1")
    A("    addi s2, s2, -1")
    A("    j rv_rx_copy")
    A("rv_rx_done:")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_spi_cs_lo          # Sn_CR = RECV consume")
    A("    addi a0, zero, 0")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 1")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x0C")
    A("    jal ra, rv_spi_xfer")
    A("    addi a0, zero, 0x40")
    A("    jal ra, rv_spi_xfer")
    A("    jal ra, rv_spi_cs_hi")
    A("    jal ra, rv_parse_offer        # a0 = msgtype or 0")
    A("    bnez a0, rv_wo_done")
    A("    lui s2, 0x100              # re-poll budget (same scale as entry)")
    A("    j rv_wo_poll")
    A("rv_wo_done:")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    lw s1, 20(sp)")
    A("    lw s2, 16(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    # --- parse_offer: RXBUF frame -> save yiaddr/sip, a0 = opt53/0 ---
    # NOTE: NO lhu/lh anywhere: rv_mem_read16's SIO/CLINT RMW path is
    # fine, but lhu on the RXBUF SRAM range is untested for odd halves;
    # byte loads keep the parse path identical to the proven ARM guest.
    A("rv_parse_offer:")
    A("    lui t0, 0x20042")
    A("    addi t0, t0, -0x200      # RXBUF 0x20041E00")
    A("    lbu t1, 12(t0)             # ethertype hi: expect 0x08")
    A("    addi t2, zero, 8")
    A("    bne t1, t2, rv_po_no")
    A("    lbu t1, 13(t0)             # ethertype lo: expect 0x00")
    A("    bnez t1, rv_po_no")
    A("    addi t0, t0, 46            # xid byte0 at RXBUF+46 (bootp+4);")
    A("                               # t0 is still RXBUF here (the lbu")
    A("                               # above use offsets, unlike ARM which")
    A("                               # stepped r0 to RXBUF+14 first).")
    A("    lbu t1, 0(t0)")
    A(f"    xori t2, t1, {xid[0]}")
    A("    bnez t2, rv_po_no")
    A("    lbu t1, 1(t0)")
    A(f"    xori t2, t1, {xid[1]}")
    A("    bnez t2, rv_po_no")
    A("    addi t0, t0, 12            # bootp+16 yiaddr")
    A("    lui t1, 0x20000")
    A("    addi t1, t1, 0x100         # YIP 0x20000100")
    A("    lbu t2, 0(t0)")
    A("    sb t2, 0(t1)")
    A("    lbu t2, 1(t0)")
    A("    sb t2, 1(t1)")
    A("    lbu t2, 2(t0)")
    A("    sb t2, 2(t1)")
    A("    lbu t2, 3(t0)")
    A("    sb t2, 3(t1)")
    A("    addi t0, t0, 220           # bootp+236 magic")
    A("    lbu t1, 0(t0)")
    A("    addi t2, zero, 99")
    A("    bne t1, t2, rv_po_no")
    A("    lbu t1, 1(t0)")
    A("    xori t2, t1, 130")
    A("    bnez t2, rv_po_no")
    A("    addi t0, t0, 4             # bootp+240 options")
    A("    lui t1, 0x20000")
    A("    addi t1, t1, 0x104         # SIP 0x20000104")
    A("    addi t2, zero, 0           # msgtype")
    A("rv_opt_loop:")
    A("    lbu t3, 0(t0)")
    A("    addi t4, zero, 255")
    A("    beq t3, t4, rv_opt_done")
    A("    addi t4, zero, 53")
    A("    bne t3, t4, rv_opt_not53")
    A("    lbu t2, 2(t0)")
    A("    j rv_po_opt_adv")
    A("rv_opt_not53:")
    A("    addi t4, zero, 54")
    A("    bne t3, t4, rv_po_opt_adv")
    A("    lbu t3, 2(t0)")
    A("    sb t3, 0(t1)")
    A("    lbu t3, 3(t0)")
    A("    sb t3, 1(t1)")
    A("    lbu t3, 4(t0)")
    A("    sb t3, 2(t1)")
    A("    lbu t3, 5(t0)")
    A("    sb t3, 3(t1)")
    A("rv_po_opt_adv:")
    A("    lbu t3, 1(t0)")
    A("    add t0, t0, t3")
    A("    addi t0, t0, 2")
    A("    j rv_opt_loop")
    A("rv_opt_done:")
    A("    mv a0, t2")
    A("    ret")
    A("rv_po_no:")
    A("    addi a0, zero, 0")
    A("    ret")
    # --- patch_request: a0 = req blob src: copy to TXBUF, stamp yip/sip.
    # req opts start TXBUF+282: opt53(3) opt50(6) opt54(6): yip val +287,
    # sip val +293. TXBUF = 0x20041C00 (below M0 RAM top, fits all arches).
    A("rv_patch_request:")
    A("    mv t5, a0                  # src = req blob")
    A("    lui t0, 0x20042")
    A("    addi t0, t0, -0x400        # TXBUF dst")
    A("    mv t6, t0")
    A(f"    addi t1, zero, {len(req)}  # len")
    A("rv_pr_copy:")
    A("    beqz t1, rv_pr_stamp")
    A("    lbu t2, 0(t5)")
    A("    sb t2, 0(t6)")
    A("    addi t5, t5, 1")
    A("    addi t6, t6, 1")
    A("    addi t1, t1, -1")
    A("    j rv_pr_copy")
    A("rv_pr_stamp:")
    A("    lui t1, 0x20000")
    A("    addi t1, t1, 0x100         # YIP 0x20000100")
    A("    addi t0, t0, 287           # TXBUF+287 requested-IP value")
    A("    lbu t2, 0(t1)")
    A("    sb t2, 0(t0)")
    A("    lbu t2, 1(t1)")
    A("    sb t2, 1(t0)")
    A("    lbu t2, 2(t1)")
    A("    sb t2, 2(t0)")
    A("    lbu t2, 3(t1)")
    A("    sb t2, 3(t0)")
    A("    addi t0, t0, 6             # TXBUF+293 server-IP value")
    A("    addi t1, t1, 4             # SIP 0x20000104")
    A("    lbu t2, 0(t1)")
    A("    sb t2, 0(t0)")
    A("    lbu t2, 1(t1)")
    A("    sb t2, 1(t0)")
    A("    lbu t2, 2(t1)")
    A("    sb t2, 2(t0)")
    A("    lbu t2, 3(t1)")
    A("    sb t2, 3(t0)")
    A("    lui t0, 0x20042")
    A("    addi t0, t0, -0x400        # return TXBUF in a0 for macraw_send")
    A("    mv a0, t0")
    A("    ret")
    # --- print_string / print_ip / blobs / rodata ---
    A("rv_print_string:                # a0 = ptr")
    A("    addi sp, sp, -16")
    A("    sw ra, 12(sp)")
    A("    sw t0, 8(sp)")
    A("    sw t1, 4(sp)")
    A("rv_ps_loop:")
    A("    lbu t1, 0(a0)")
    A("    beqz t1, rv_ps_done")
    A("    lui t0, 0x40070")
    A("    sw t1, 0(t0)")
    A("    addi a0, a0, 1")
    A("    j rv_ps_loop")
    A("rv_ps_done:")
    A("    lw ra, 12(sp)")
    A("    lw t0, 8(sp)")
    A("    lw t1, 4(sp)")
    A("    addi sp, sp, 16")
    A("    ret")
    A("rv_print_ip:                    # prints YIP a.b.c.d (no newline)")
    A("    addi sp, sp, -32")
    A("    sw ra, 28(sp)")
    A("    sw s0, 24(sp)")
    A("    lui s0, 0x20000")
    A("    addi s0, s0, 0x100         # YIP")
    A("    addi t6, zero, 4           # octets left")
    A("rv_ip_oct:")
    A("    lbu a0, 0(s0)")
    A("    jal ra, rv_print_u8")
    A("    addi t6, t6, -1")
    A("    beqz t6, rv_ip_done")
    A("    addi a0, zero, 46          # '.'")
    A("    lui t0, 0x40070")
    A("    sw a0, 0(t0)")
    A("    addi s0, s0, 1")
    A("    j rv_ip_oct")
    A("rv_ip_done:")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    A("rv_print_u8:                    # a0 = 0..255 -> decimal, no leading zeros")
    A("    addi sp, sp, -32")
    A("    sw ra, 28(sp)")
    A("    sw s0, 24(sp)")
    A("    sw s1, 20(sp)")
    A("    sw s2, 16(sp)")
    A("    mv s0, a0                  # value")
    A("    addi s1, zero, 0           # printed-any flag")
    A("    addi t0, zero, 100")
    A("    jal ra, rv_print_digit        # (s0=value, s1=flag, t0=div)")
    A("    addi t0, zero, 10")
    A("    jal ra, rv_print_digit")
    A("    addi t0, zero, 1")
    A("    jal ra, rv_print_digit")
    A("    lw ra, 28(sp)")
    A("    lw s0, 24(sp)")
    A("    lw s1, 20(sp)")
    A("    lw s2, 16(sp)")
    A("    addi sp, sp, 32")
    A("    ret")
    A("rv_print_digit:                 # s0=value t0=div s1=flag -> UART digit")
    A("    mv t1, s0")
    A("    addi t2, zero, 0           # quotient")
    A("rv_dg_loop:")
    A("    bltu t1, t0, rv_dg_done")
    A("    sub t1, t1, t0")
    A("    addi t2, t2, 1")
    A("    j rv_dg_loop")
    A("rv_dg_done:")
    A("    mv s0, t1                  # remainder back to value")
    A("    addi t3, zero, 1")
    A("    beq t0, t3, rv_dg_show        # ones always print")
    A("    bnez t2, rv_dg_show")
    A("    bnez s1, rv_dg_show0          # tens prints 0 if hundreds did")
    A("    ret")
    A("rv_dg_show0:")
    A("    addi t2, zero, 0")
    A("rv_dg_show:")
    A("    addi t2, t2, 48")
    A("    lui t4, 0x40070")
    A("    sw t2, 0(t4)")
    A("    addi s1, zero, 1")
    A("    ret")
    # --- rodata: strings + blobs (auipc refs above resolve via rvlink) ---
    A("")
    A("    .section .rodata")
    A("    .align 2")
    A('.Ls1: .asciz "ETH DHCP-START\\n"')
    A('.Ls2: .asciz "ETH MACRAW-OK\\n"')
    A('.Ls3: .asciz "ETH FAIL VERSION\\n"')
    A('.Ls4: .asciz "ETH FAIL OPEN\\n"')
    A('.Ls5: .asciz "ETH FAIL\\n"')
    A('.Ls6: .asciz "ETH OFFER IP="')
    A('.Ls7: .asciz "ETH IP="')
    A('.Ls8: .asciz "\\n"')
    A('.Ls9: .asciz "ETH DONE\\n"')
    A('.Ls10: .asciz "ETH FAIL OFFER-TIMEOUT\\n"')
    A('.Ls11: .asciz "ETH FAIL ACK-TIMEOUT\\n"')
    A(f"disc_blob:  # DISCOVER {len(disc)}B")
    for i in range(0, len(disc), 12):
        A("    .byte " + ", ".join(f"{b}" for b in disc[i:i + 12]))
    A(f"req_blob:   # REQUEST {len(req)}B")
    for i in range(0, len(req), 12):
        A("    .byte " + ", ".join(f"{b}" for b in req[i:i + 12]))
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
