#!/usr/bin/env python3
"""Generate RV32 bare-metal demos for Bramble Hazard3 (RP2350 RISC-V).

Position-independent rv32ima assembly (no compressed insns, auipc+addi
string refs, hand-split immediates) so test-firmware/rvlink.py links it
without a RISC-V linker. Run: python3 gen_rv32.py (writes *_rv32.S).
"""
import os

D = os.path.dirname(os.path.abspath(__file__))

PROLOGUE = """/* {title} (RP2350 RISC-V, Hazard3 RV32IMAC).
 * Generated by gen_rv32.py - do not hand-edit (edit the generator).
 * Flash base 0x10000000 (entry via bootrom), SRAM to 0x20082000.
 */
    .text
    .globl _start
    .align 2
_start:
    lui sp, 0x20082            # SP = top of SRAM
    lui t0, 0x40070            # UART0 base
    addi t1, zero, 0x301
    sw t1, 0x30(t0)            # UARTEN|TXE|RXE
"""

HELPERS = """
print_string:                # a0 = ptr
    addi sp, sp, -16
    sw ra, 12(sp)
    sw t0, 8(sp)
    sw t1, 4(sp)
ps_loop:
    lbu t1, 0(a0)
    beqz t1, ps_done
    lui t0, 0x40070
    sw t1, 0(t0)
    addi a0, a0, 1
    j ps_loop
ps_done:
    lw ra, 12(sp)
    lw t0, 8(sp)
    lw t1, 4(sp)
    addi sp, sp, 16
    ret

print_hex32:                 # a0 = word: 8 hex digits + newline
    addi sp, sp, -16
    sw ra, 12(sp)
    sw t1, 8(sp)
    sw t2, 4(sp)
    addi t2, zero, 8
    mv t1, a0
hex_digit:
    srli a0, t1, 28
    slli t1, t1, 4
    addi t0, zero, 10
    bgeu a0, t0, hex_alpha
    addi a0, a0, 0x30
    j hex_out
hex_alpha:
    addi a0, a0, 0x37
hex_out:
    lui t0, 0x40070
    sw a0, 0(t0)
    addi t2, t2, -1
    bnez t2, hex_digit
    addi a0, zero, 0x0A
    lui t0, 0x40070
    sw a0, 0(t0)
    lw ra, 12(sp)
    lw t1, 8(sp)
    lw t2, 4(sp)
    addi sp, sp, 16
    ret

uart_getc:                   # -> a0 = byte (blocks)
    lui t0, 0x40070
ug_wait:
    lw t1, 0x18(t0)
    andi t1, t1, 0x10
    bnez t1, ug_wait
    lw a0, 0(t0)
    andi a0, a0, 0xFF
    ret
"""

EPILOGUE = """
halt:
    j halt
"""


def li32(reg, val):
    """lui+addi (or single addi) to materialize a 32-bit constant."""
    val &= 0xFFFFFFFF
    lo = val & 0xFFF
    if lo >= 0x800:
        lo -= 0x1000
    hi = (val - lo) >> 12
    hi &= 0xFFFFF
    if hi == 0:
        return [f"    addi {reg}, zero, {lo}"]
    out = [f"    lui {reg}, {hi:#x}"]
    if lo != 0:
        out.append(f"    addi {reg}, {reg}, {lo}")
    return out


class Demo:
    def __init__(self, name, title):
        self.name = name
        self.title = title
        self.body = []
        self.rodata = []
        self.nstr = 0

    def pstr(self, text):
        self.nstr += 1
        lab = f".Ls{self.nstr}"
        esc = (text.replace('\\', '\\\\').replace('"', '\\"')
                 .replace('\n', '\\n'))
        self.body.append(f".Lr{self.nstr}: auipc a0, %pcrel_hi({lab})")
        self.body.append(f"    addi a0, a0, %pcrel_lo(.Lr{self.nstr})")
        self.body.append("    jal ra, print_string")
        self.rodata.append(f"{lab}: .asciz \"{esc}\"")
        return lab

    def emit(self, line):
        self.body.append("    " + line if line and not line.startswith('.') else line)

    def li(self, reg, val):
        for ln in li32(reg, val):
            self.emit(ln.strip())

    def wreg(self, addr, val):
        """Write 32-bit val to absolute address (lui/addi + sw)."""
        ahi = (addr >> 12) & 0xFFFFF
        alo = addr & 0xFFF
        if alo >= 0x800:
            ahi = (ahi + 1) & 0xFFFFF
            alo -= 0x1000
        self.emit(f"lui t0, {ahi:#x}")
        if alo != 0:
            self.emit(f"addi t0, t0, {alo}")
        for ln in li32("t1", val):
            self.emit(ln.strip())
        self.emit("sw t1, 0(t0)")

    def rreg(self, addr, reg="t1"):
        """Read absolute address into reg, result in a0."""
        ahi = (addr >> 12) & 0xFFFFF
        alo = addr & 0xFFF
        if alo >= 0x800:
            ahi = (ahi + 1) & 0xFFFFF
            alo -= 0x1000
        self.emit(f"lui t0, {ahi:#x}")
        if alo != 0:
            self.emit(f"addi t0, t0, {alo}")
        self.emit(f"lw {reg}, 0(t0)")

    def render(self):
        out = [PROLOGUE.format(title=self.title)]
        out += self.body
        out += [EPILOGUE, HELPERS, "", "    .section .rodata", "    .align 2"]
        out += self.rodata
        return "\n".join(out) + "\n"


DEMOS = []


def simple_reg_demo(name, title, start_msg, base, writes, done_msg):
    """Register writes + static prints. writes=[(off,val,ok_msg)]."""
    d = Demo(name, title)
    d.pstr(start_msg)
    for off, val, ok in writes:
        d.wreg(base + off, val)
        d.pstr(ok)
    d.pstr(done_msg)
    DEMOS.append(d)
    return d


# --- hello ---
d = Demo("hello_rv32", "Hello World")
d.pstr("Hello from Bramble RV32!\n")
DEMOS.append(d)

# --- gpio (SIO, LED pin 25) ---
d = Demo("gpio_rv32", "GPIO Test")
d.pstr("GPIO Test Starting\n")
d.wreg(0xD0000000 + 0x24, 1 << 25)  # OE_SET
d.pstr("GPIO 25 configured as output\n")
d.wreg(0xD0000000 + 0x14, 1 << 25)  # OUT_SET
d.pstr("LED ON\n")
d.wreg(0xD0000000 + 0x18, 1 << 25)  # OUT_CLR
d.pstr("LED OFF\n")
d.wreg(0xD0000000 + 0x14, 1 << 25)
d.pstr("Final state: LED OFF\n")
d.pstr("GPIO Test Complete!\n")
DEMOS.append(d)

# --- timer (RP2350 TIMER0 reads) ---
d = Demo("timer_rv32", "Timer Test")
d.pstr("Timer Test Starting (TIMER0 0x400B0000)\n")
d.rreg(0x400B000C)
d.emit("mv s0, t1")
d.pstr("Timer value 1 read\n")
d.rreg(0x400B000C)
d.pstr("Timer value 2 read\n")
d.pstr("Elapsed time: (see debug output)\n")
d.pstr("Timer Test Complete!\n")
DEMOS.append(d)

# --- peripheral register demos (RP2350 bases) ---
simple_reg_demo("spi_rv32", "SPI Test",
                "SPI Test Starting (SPI PL022 0x40080000)\n",
                0x40080000, [(0, 1, "SPI register 0x40080000 write OK\n")],
                "SPI Test Complete!\n")
simple_reg_demo("i2c_rv32", "I2C Test",
                "I2C Test Starting (I2C 0x40090000)\n",
                0x40090000, [(0, 1, "I2C register 0x40090000 write OK\n")],
                "I2C Test Complete!\n")
simple_reg_demo("pwm_rv32", "PWM Test",
                "PWM Test Starting (PWM 0x400A8000)\n",
                0x400A8000, [(0, 1, "PWM register 0x400A8000 write OK\n")],
                "PWM Test Complete!\n")
simple_reg_demo("adc_rv32", "ADC Test",
                "ADC Test Starting (ADC 0x400A0000)\n",
                0x400A0000, [(0, 1, "ADC register 0x400A0000 write OK\n")],
                "ADC Test Complete!\n")
simple_reg_demo("dma_rv32", "DMA Test",
                "DMA Test Starting (DMA 0x50000000)\n",
                0x50000000, [(0, 1, "DMA register 0x50000000 write OK\n")],
                "DMA Test Complete!\n")
simple_reg_demo("pio_rv32", "PIO Test",
                "PIO Test Starting (PIO 0x50200000)\n",
                0x50200000, [(0, 1, "PIO register 0x50200000 write OK\n")],
                "PIO Test Complete!\n")
simple_reg_demo("usb_rv32", "USB Test",
                "USB Test Starting (USB 0x50100000)\n",
                0x50100000, [(0, 1, "USB register 0x50100000 write OK\n")],
                "USB Test Complete!\n")

# --- clocks (RP2350 bases, values printed as hex) ---
d = Demo("clocks_rv32", "Clocks Test")
d.pstr("Clocks Test Starting (RESETS/CLOCKS/PLL_SYS)\n")
for addr, msg in [(0x40020000, "RESETS RESET register 0x40020000 = "),
                  (0x40010044, "CLK_SYS_SELECTED register 0x40010044 = "),
                  (0x40050000, "PLL_SYS_CS register 0x40050000 = ")]:
    d.pstr(msg)
    d.rreg(addr)
    d.emit("mv a0, t1")
    d.emit("jal ra, print_hex32")
d.pstr("Clocks Test Complete!\n")
DEMOS.append(d)

# --- psm ---
d = Demo("psm_rv32", "PSM Test")
d.pstr("PSM Test Starting (PSM 0x40018000)\n")
for addr, msg in [(0x40018004, "PSM FRCE_OFF register 0x40018004 = "),
                  (0x40018008, "PSM FRCE_ON register 0x40018008 = "),
                  (0x40018020, "PSM DONE register 0x40018020 = ")]:
    d.pstr(msg)
    d.rreg(addr)
    d.emit("mv a0, t1")
    d.emit("jal ra, print_hex32")
d.pstr("PSM Test Complete!\n")
DEMOS.append(d)

# --- ws2812 (PIO0 SM0, OUT + side-set + JMP; words via .word data) ---
d = Demo("ws2812_rv32", "WS2812 Test")
d.pstr("WS2812 Test Starting (PIO0 SM0, side-set, pin 16)\n")
d.emit("ws_progaddr:")
d.emit("auipc t3, %pcrel_hi(.Lprogdata)")
d.emit("addi t3, t3, %pcrel_lo(ws_progaddr)")
d.emit("lui s0, 0x50200")          # PIO0 base (kept across prints)
d.emit("addi t4, zero, 0")         # i = 0
d.emit("ws_copy:")
d.emit("slli t5, t4, 2")
d.emit("add t5, t3, t5")
d.emit("lw t5, 0(t5)")
d.emit("slli t6, t4, 2")
d.emit("addi t6, t6, 0x48")
d.emit("add t6, s0, t6")
d.emit("sw t5, 0(t6)")
d.emit("addi t4, t4, 1")
d.emit("addi t6, zero, 8")
d.emit("bltu t4, t6, ws_copy")
# PINCTRL: sideset 1 @ 16
d.li("t1", (1 << 29) | (16 << 10))
d.emit("sw t1, 0xDC(s0)")
# EXECCTRL: wrap top 7
d.li("t1", 7 << 12)
d.emit("sw t1, 0xCC(s0)")
# SHIFTCTRL: autopull + OUT shift right
d.li("t1", (1 << 17) | (1 << 19))
d.emit("sw t1, 0xD0(s0)")
# CLKDIV: every cycle
d.li("t1", 1 << 16)
d.emit("sw t1, 0xC8(s0)")
# TXF pixel + enable SM0
d.li("t1", 0x00FF0000)
d.emit("sw t1, 0x10(s0)")
d.emit("addi t1, zero, 1")
d.emit("sw t1, 0(s0)")
# poll ADDR == 7, bounded
d.li("t2", 200000)
d.emit("ws_wait:")
d.emit("lw t1, 0xD4(s0)")
d.emit("addi t3, zero, 7")
d.emit("beq t1, t3, ws_done")
d.emit("addi t2, t2, -1")
d.emit("bnez t2, ws_wait")
d.pstr("WS2812 TIMEOUT waiting for SM\n")
d.emit("j ws_finish")
d.emit("ws_done:")
d.pstr("WS2812 24 bits sent (GRB=FF0000), SM idle at done loop\n")
d.emit("ws_finish:")
# LED25 on via SIO
d.li("t1", 1 << 25)
d.emit("lui t0, 0xD0000")
d.emit("sw t1, 0x24(t0)")
d.emit("sw t1, 0x14(t0)")
d.pstr("WS2812 Test Complete!\n")
d.rodata.append(".align 2\n.Lprogdata: .word 0x80A0, 0xE0D7, 0x6121, 0x1125, 0x1206, 0xA142, 0x1182, 0x1007")
DEMOS.append(d)

# --- rtc (RP2350 RTC readout) ---
d = Demo("rtc_rv32", "RTC Test")
d.pstr("RTC Test Starting (RTC 0x4005C000)\n")
d.emit("lui s0, 0x4005C")          # RTC base
d.li("t1", 0x07E20906)
d.emit("sw t1, 0x04(s0)")          # SETUP_0
d.li("t1", 0x000C0000)
d.emit("sw t1, 0x08(s0)")          # SETUP_1
d.li("t1", 0x11)
d.emit("sw t1, 0x0C(s0)")          # LOAD + ENABLE
d.pstr("RTC CTRL register = ")
d.emit("lw a0, 0x0C(s0)")
d.emit("jal ra, print_hex32")
d.pstr("RTC datetime 1 register = ")
d.emit("lw a0, 0x18(s0)")
d.emit("jal ra, print_hex32")
d.pstr("RTC datetime 0 register = ")
d.emit("lw a0, 0x1C(s0)")
d.emit("jal ra, print_hex32")
d.pstr("RTC Test Complete!\n")
DEMOS.append(d)

# --- uart_echo (interactive line echo) ---
d = Demo("uart_echo_rv32", "UART Echo Test")
d.pstr("UART Echo Test: type a line and press Enter\n")
d.emit("lui s0, 0x20081")          # line buffer 0x20081000
d.emit("addi s1, zero, 0")         # length
d.emit("echo_loop:")
d.emit("lui t0, 0x40070")
d.emit("echo_wait:")
d.emit("lw t1, 0x18(t0)")
d.emit("andi t1, t1, 0x10")
d.emit("bnez t1, echo_wait")
d.emit("lw t1, 0(t0)")
d.emit("andi t1, t1, 0xFF")
d.emit("addi t2, zero, 0x0D")
d.emit("beq t1, t2, echo_done")
d.emit("addi t2, zero, 0x0A")
d.emit("beq t1, t2, echo_done")
d.emit("addi t2, zero, 64")
d.emit("bgeu s1, t2, echo_loop")
d.emit("add s2, s0, s1")
d.emit("sb t1, 0(s2)")
d.emit("addi s1, s1, 1")
d.emit("sw t1, 0(t0)")             # echo
d.emit("j echo_loop")
d.emit("echo_done:")
d.emit("add s2, s0, s1")
d.emit("sb zero, 0(s2)")           # NUL (word store ok: next 4 aligned? buffer+len may be unaligned!)
d.pstr("Echo: ")
d.emit("mv a0, s0")
d.emit("jal ra, print_string")
d.pstr("\n")
d.pstr("UART Echo Test Complete!\n")
DEMOS.append(d)

# --- name_prompt (interactive greeting) ---
d = Demo("name_prompt_rv32", "Name Prompt Test")
d.pstr("What is your name? \n")
d.emit("lui s0, 0x20081")
d.emit("addi s1, zero, 0")
d.emit("np_loop:")
d.emit("lui t0, 0x40070")
d.emit("np_wait:")
d.emit("lw t1, 0x18(t0)")
d.emit("andi t1, t1, 0x10")
d.emit("bnez t1, np_wait")
d.emit("lw t1, 0(t0)")
d.emit("andi t1, t1, 0xFF")
d.emit("addi t2, zero, 0x0D")
d.emit("beq t1, t2, np_done")
d.emit("addi t2, zero, 0x0A")
d.emit("beq t1, t2, np_done")
d.emit("addi t2, zero, 62")
d.emit("bgeu s1, t2, np_loop")
d.emit("add s2, s0, s1")
d.emit("sb t1, 0(s2)")
d.emit("addi s1, s1, 1")
d.emit("sw t1, 0(t0)")
d.emit("j np_loop")
d.emit("np_done:")
d.emit("add s2, s0, s1")
d.emit("sb zero, 0(s2)")
d.pstr("Hello, ")
d.emit("mv a0, s0")
d.emit("jal ra, print_string")
d.pstr("!\n")
d.pstr("Name Prompt Test Complete!\n")
DEMOS.append(d)

# --- interrupt (CLINT mtimecmp + M-mode trap) ---
d = Demo("interrupt_rv32", "Timer Interrupt Test")
d.pstr("Timer Interrupt Test Starting (CLINT mtimecmp + M trap)\n")
d.emit("lui t0, 0x20080")
d.emit("sw zero, 0(t0)")           # flag cell = 0
d.emit("lui t0, 0xD0000")          # CLINT base 0xD0000100
d.emit("addi t0, t0, 0x100")
d.li("t1", 20000)
d.emit("sw t1, 0x08(t0)")          # MTIMECMP0_LO
d.emit("sw zero, 0x0C(t0)")        # MTIMECMP0_HI
d.emit("inthandler_addr:")
d.emit("auipc t0, %pcrel_hi(int_handler)")
d.emit("addi t0, t0, %pcrel_lo(inthandler_addr)")
d.emit("csrw mtvec, t0")
d.li("t0", 0x80)
d.emit("csrrs zero, mie, t0")      # enable MTI
d.li("t0", 8)
d.emit("csrrs zero, mstatus, t0")  # enable MIE
d.emit("lui s0, 0x20080")
d.li("t2", 20000000)
d.emit("int_poll:")
d.emit("lw t0, 0(s0)")
d.emit("bnez t0, int_fired")
d.emit("addi t2, t2, -1")
d.emit("bnez t2, int_poll")
d.pstr("Timer IRQ NOT received\n")
d.emit("j int_end")
d.emit("int_fired:")
d.pstr("Timer IRQ handled, hart woke via trap\n")
d.emit("int_end:")
d.pstr("Timer Interrupt Test Complete!\n")
d.emit("j int_halt")
d.emit("int_halt:")
d.emit("j int_halt")
d.emit(".align 2")
d.emit("int_handler:")
d.li("t0", 0x80)
d.emit("csrrc zero, mie, t0")      # mask timer IRQ (no re-trap)
d.emit("lui t0, 0x20080")
d.li("t1", 1)
d.emit("sw t1, 0(t0)")             # flag = 1
d.emit("mret")
DEMOS.append(d)

# --- dualcore (Hart 0 launches Hart 1 via SIO mailbox) ---
d = Demo("dualcore_rv32", "Dual-Core Hart Launch")
d.pstr("Dual-Core Test Starting (Hart 0 + Hart 1)\n")
d.emit("lui t0, 0x20080")
d.emit("sw zero, 0(t0)")           # flag cell = 0
d.emit("hart1_site:")
d.emit("auipc t0, %pcrel_hi(hart1_entry)")
d.emit("addi t0, t0, %pcrel_lo(hart1_site)")
d.emit("lui t1, 0xD0000")          # SIO 0xD0000000
d.emit("sw t0, 0x1C0(t1)")         # ENTRY = hart1_entry
d.li("t0", 0x20081000)
d.emit("sw t0, 0x1C4(t1)")         # SP (hart1 stack)
d.emit("sw zero, 0x1C8(t1)")       # ARG = 0
d.li("t0", 1)
d.emit("sw t0, 0x1CC(t1)")         # LAUNCH
d.pstr("Hart 0 launched Hart 1\n")
d.emit("lui s0, 0x20080")
d.li("t2", 20000000)
d.emit("dc_poll:")
d.emit("lw t0, 0(s0)")
d.emit("bnez t0, dc_done")
d.emit("addi t2, t2, -1")
d.emit("bnez t2, dc_poll")
d.pstr("FAIL: Hart 1 never signalled\n")
d.emit("j dc_end")
d.emit("dc_done:")
d.pstr("Hart 1 signalled, both harts ran\n")
d.emit("dc_end:")
d.pstr("Dual-Core Test Complete!\n")
d.emit("j dc_halt")
d.emit("dc_halt:")
d.emit("j dc_halt")
d.emit(".align 2")
d.emit("hart1_entry:")
d.emit("lui sp, 0x20081")          # hart1 stack (also set by launcher)
d.li("t2", 200000)
d.emit("hart1_delay:")             # let Hart 0 finish its line first
d.emit("addi t2, t2, -1")
d.emit("bnez t2, hart1_delay")
d.pstr("Hello from Hart 1\n")
d.emit("lui t0, 0x20080")
d.li("t1", 1)
d.emit("sw t1, 0(t0)")             # flag = 1
d.emit("hart1_done:")
d.emit("j hart1_done")
DEMOS.append(d)

if __name__ == "__main__":
    for d in DEMOS:
        if d is None:
            continue
        path = os.path.join(D, d.name + ".S")
        open(path, "w").write(d.render())
        print("wrote", path)
